"""Standalone Connector Pipeline: test1_etl
Generated by SDLC Data Engineer Agent.
Architecture: GCS -> Local Staging -> BIGQUERY
Mock dummy data generation is completely disabled — real extraction & loading only.
"""
import os
import sys
import logging
import argparse
from datetime import datetime

import pandas as pd
from pipeline.extractor import GCSExtractor
from pipeline.transformer import DataTransformer
from pipeline.validator import DataValidator
from pipeline.loader import BigQueryLoader

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [%(name)s] %(message)s",
)
logger = logging.getLogger("test1_etl")


class PipelineRunner:
    """Executes the end-to-end ETL flow: GCS -> Transform -> Validate -> BigQuery."""

    def __init__(self, execution_date: str = None):
        self.execution_date = execution_date or datetime.utcnow().strftime("%Y-%m-%d")
        self.staging_dir = os.path.join("staging", "test1_etl", self.execution_date)
        os.makedirs(self.staging_dir, exist_ok=True)
        self.staging_file = os.path.join(self.staging_dir, "data.parquet")

        self.extractor = GCSExtractor()
        self.transformer = DataTransformer()
        self.validator = DataValidator()
        self.loader = BigQueryLoader()

    def extract(self) -> int:
        """Extracts data from real GCS source into staging format."""
        logger.info("Starting extraction from GCS source...")
        df = self.extractor.extract_to_dataframe()
        row_count = len(df)
        df.to_parquet(self.staging_file, index=False)
        logger.info("Extracted %d records from GCS to %s", row_count, self.staging_file)
        return row_count

    def transform(self) -> int:
        """Sanitizes column names, normalizes currencies & footnotes, validates circuit breaker."""
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file is empty. Nothing to transform.")
            return 0

        df = pd.read_parquet(self.staging_file)
        raw_count = len(df)
        if raw_count == 0:
            logger.warning("Staging DataFrame is empty. Nothing to transform.")
            return 0

        logger.info("Transforming %d raw records...", raw_count)
        transformed_df = self.transformer.transform(df)
        valid_df = self.validator.validate(transformed_df)

        valid_df.to_parquet(self.staging_file, index=False)
        logger.info("Transform complete: raw=%d, valid=%d", raw_count, len(valid_df))
        return len(valid_df)

    def load(self) -> bool:
        """Loads staged records into BigQuery destination."""
        logger.info("Loading staged file %s into BigQuery...", self.staging_file)
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file is empty or missing. Skipping load.")
            return True

        df = pd.read_parquet(self.staging_file)
        return self.loader.load_dataframe(df)

    def run(self) -> int:
        """Executes the end-to-end connector pipeline with fail-fast semantics."""
        logger.info("=== Starting Connector Pipeline Execution ===")
        try:
            records = self.extract()
            if records == 0:
                logger.warning("Extraction completed with 0 records.")
            valid_count = self.transform()
            if records > 0 and valid_count == 0:
                logger.error(
                    "FATAL: Extracted %d records but 0 survived transformation. Failing pipeline.",
                    records
                )
                raise RuntimeError("Extracted records failed transformation.")
            self.load()
            logger.info("=== Pipeline Execution Finished Successfully ===")
            return 0
        except Exception as exc:
            logger.critical("Pipeline execution FAILED: %s", exc, exc_info=True)
            raise


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Connector Pipeline Runner")
    parser.add_argument("--date", help="Execution date (YYYY-MM-DD)", default=None)
    args = parser.parse_args()

    try:
        runner = PipelineRunner(execution_date=args.date)
        exit_code = runner.run()
        if exit_code != 0:
            sys.exit(exit_code)
    except Exception as exc:
        logging.getLogger("test1_etl").critical("Pipeline failed with unhandled error: %s", exc, exc_info=True)
        sys.exit(1)
