"""Standalone Connector Pipeline: postgres_to_bigquery
Generated by SDLC Data Engineer Agent.
Architecture: POSTGRESQL -> Local Staging -> BIGQUERY
Mock dummy data generation is completely disabled — real extraction & loading only.
"""
import os
import sys
import json
import logging
import argparse
from datetime import datetime

# Dependencies
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [%(name)s] %(message)s",
)
logger = logging.getLogger("postgres_to_bigquery")


class PipelineRunner:
    def __init__(self, execution_date: str = None):
        self.execution_date = execution_date or datetime.utcnow().strftime("%Y-%m-%d")
        self.staging_dir = os.path.join("staging", "postgres_to_bigquery", self.execution_date)
        os.makedirs(self.staging_dir, exist_ok=True)
        self.staging_file = os.path.join(self.staging_dir, "data.parquet")

    def extract(self) -> int:
        """Extracts data from real postgresql into staging format.
        
        Zero-mock policy: if credentials or sources are unavailable, raises an error immediately.
        """
        logger.info("Starting real extraction from source: postgresql...")
        db_url = os.getenv("DATABASE_URL") or os.getenv("POSTGRES_URL")
        sql_engine = None
        sql_connector = None

        instance_connection_name = (
            os.getenv("INSTANCE_CONNECTION_NAME")
            or os.getenv("POSTGRES_INSTANCE_CONNECTION_NAME")
            or os.getenv("CLOUD_SQL_CONNECTION_NAME")
            or ""
        )
        host = os.getenv("POSTGRES_HOST") or os.getenv("DB_HOST", "")
        if not instance_connection_name and host and host.count(":") == 2:
            instance_connection_name = host
            host = ""

        port = os.getenv("POSTGRES_PORT") or os.getenv("DB_PORT", "5432")
        user = os.getenv("POSTGRES_USER") or os.getenv("DB_USER", "")
        dbname = os.getenv("POSTGRES_DB") or os.getenv("DB_NAME", "")
        # NOTE: POSTGRES_PASSWORD is intentionally NOT read here.
        # All Cloud SQL connections use IAM database authentication.

        # Cloud SQL Python Connector with mandatory IAM Authentication
        if instance_connection_name and user:
            try:
                import sqlalchemy
                from google.cloud.sql.connector import Connector, IPTypes
                logger.info(
                    "Connecting via Cloud SQL Python Connector for %s (IAM auth, user=%s)",
                    instance_connection_name, user
                )
                sql_connector = Connector()
                _ip_type = IPTypes.PRIVATE if (os.getenv("CLOUD_SQL_IP_TYPE", "PRIVATE").upper() == "PRIVATE") else IPTypes.PUBLIC
                def _getconn():
                    return sql_connector.connect(
                        instance_connection_name,
                        "pg8000",
                        user=user,
                        db=dbname,
                        enable_iam_auth=True,  # ALWAYS True — IAM auth is mandatory
                        ip_type=_ip_type,
                    )
                sql_engine = sqlalchemy.create_engine("postgresql+pg8000://", creator=_getconn)
            except Exception as _conn_err:
                logger.error(
                    "FATAL: Cloud SQL Python Connector initialization failed: %s.",
                    _conn_err
                )
                raise RuntimeError(f"Cloud SQL connector failed: {_conn_err}") from _conn_err

        con_target = sql_engine if sql_engine is not None else db_url
        if not con_target:
            raise EnvironmentError(
                "FATAL: Database connection parameters missing. "
                "Provide INSTANCE_CONNECTION_NAME + POSTGRES_USER + POSTGRES_DB for Cloud SQL IAM auth, "
                "or DATABASE_URL for direct connection. Mock dummy data is disabled."
            )

        source_table = os.getenv("POSTGRES_TABLE", "test_data")
        query = f"SELECT * FROM {source_table}"
        logger.info("Executing extraction query against PostgreSQL: %s", query)
        try:
            df = pd.read_sql(query, con=con_target)
        except Exception as _query_err:
            logger.error("Query execution failed: %s", _query_err)
            raise RuntimeError(f"PostgreSQL extraction query failed: {_query_err}") from _query_err
        finally:
            if sql_engine is not None:
                sql_engine.dispose()
            if sql_connector is not None:
                sql_connector.close()

        row_count = len(df)
        df.to_parquet(self.staging_file, index=False)
        logger.info("Extracted %d real records to %s", row_count, self.staging_file)
        return row_count

    def transform(self) -> int:
        """Schema-adaptive transformation with flexible parsing.

        - Discovers columns dynamically from the extracted DataFrame.
        - Trims whitespace across string columns.
        - Standardizes null representations.
        - Parses date/timestamp columns into UTC ISO-8601.
        - Coerces numeric columns gracefully.
        - Deduplicates identical rows.
        - Circuit breaker: if 100% of rows fail validation, exits with code 1.
        """
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file is empty. Nothing to transform.")
            return 0

        df = pd.read_parquet(self.staging_file)
        raw_count = len(df)
        if raw_count == 0:
            logger.warning("Staging DataFrame is empty. Nothing to transform.")
            return 0

        logger.info("Transforming %d raw records. Columns: %s", raw_count, list(df.columns))

        # 1. Whitespace trimming and string normalization
        for col in df.select_dtypes(include=["object", "string"]).columns:
            df[col] = df[col].astype(str).str.strip()
            df[col] = df[col].replace({"nan": None, "None": None, "NULL": None, "null": None, "N/A": None, "": None})

        # 2. Date / Timestamp normalization to UTC
        for col in df.columns:
            if "date" in col.lower() or "time" in col.lower() or "created" in col.lower() or "updated" in col.lower():
                df[col] = pd.to_datetime(df[col], utc=True, errors="coerce")
                logger.info("Converted column %s to UTC TIMESTAMP", col)

        # 3. Numeric normalization
        for col in ["value", "amount", "price", "count", "quantity"]:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors="coerce")
                logger.info("Normalized numeric column %s", col)

        # 4. Deduplication
        if "id" in df.columns:
            df = df.drop_duplicates(subset=["id"], keep="last")
        else:
            df = df.drop_duplicates(keep="last")

        # 5. Basic validity filter (non-empty rows only)
        df_valid = df.dropna(how="all")
        quarantined = raw_count - len(df_valid)
        if quarantined > 0:
            logger.warning("Quarantined %d invalid records", quarantined)

        # 6. Circuit breaker
        if raw_count > 0 and len(df_valid) == 0:
            logger.error(
                "FATAL: 100%% of %d raw records were quarantined. "
                "This indicates a schema contract violation between "
                "the source data and the pipeline expectations. "
                "Failing the pipeline.", raw_count
            )
            sys.exit(1)

        # 7. Add ingestion audit timestamp
        df_valid = df_valid.copy()
        if "ingested_at" not in df_valid.columns:
            df_valid["ingested_at"] = pd.Timestamp.utcnow()

        # Overwrite staging file with cleaned data
        df_valid.to_parquet(self.staging_file, index=False)
        logger.info(
            "Transform complete: raw=%d, valid=%d, quarantined=%d",
            raw_count, len(df_valid), quarantined,
        )
        return len(df_valid)

    def load(self) -> bool:
        """Loads staged records into real bigquery destination.
        
        Zero-mock policy: if destination load fails, raises RuntimeError immediately.
        """
        logger.info("Loading staged file %s into bigquery (analytics.postgres_test2)...", self.staging_file)
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file %s is empty or missing. Skipping load phase.", self.staging_file)
            return True
        project_id = os.getenv("GCP_PROJECT_ID") or os.getenv("PROJECT_ID") or os.getenv("GOOGLE_CLOUD_PROJECT") or os.getenv("GCLOUD_PROJECT") or "upbeat-repeater-477110-q6"
        dataset_id = os.getenv("BIGQUERY_DATASET", "analytics")
        table_id = os.getenv("BIGQUERY_TABLE", "postgres_test2")
        write_mode = "overwrite"

        from google.cloud import bigquery
        client = bigquery.Client(project=project_id)
        table_ref = f"{project_id}.{dataset_id}.{table_id}"

        df = pd.read_parquet(self.staging_file)

        job_config = bigquery.LoadJobConfig(
            write_disposition=bigquery.WriteDisposition.WRITE_APPEND if write_mode == "append" else bigquery.WriteDisposition.WRITE_TRUNCATE,
        )
        schema_file = None
        for cand in [
            os.path.join("schemas", "postgres_test2_schema.json"),
            os.path.join("schemas", "postgres_to_bigquery_schema.json"),
            os.path.join("schemas", "target_table_schema.json"),
        ]:
            if os.path.isfile(cand):
                schema_file = cand
                break
        if schema_file:
            try:
                job_config.schema = client.schema_from_json(schema_file)
                logger.info("Attached explicit BigQuery schema from %s", schema_file)
            except Exception as schema_err:
                raise RuntimeError(f"Could not load BigQuery schema from {schema_file}: {schema_err}") from schema_err

        try:
            job = client.load_table_from_dataframe(df, table_ref, job_config=job_config)
            job.result()  # Blocks until BigQuery load completes
        except Exception as load_err:
            logger.error("BigQuery load job failed: %s", load_err)
            raise RuntimeError(f"FATAL: BigQuery load job failed: {load_err}") from load_err

        if job.errors:
            raise RuntimeError(f"FATAL: BigQuery load job returned errors: {job.errors}")

        logger.info("Successfully loaded %d records into BigQuery table: %s", len(df), table_ref)
        return True

    def run(self) -> int:
        """Executes the end-to-end connector pipeline with fail-fast semantics."""
        logger.info("=== Starting Connector Pipeline Execution ===")
        try:
            records = self.extract()
            if records == 0:
                logger.warning("Extraction completed with 0 records.")
            valid_count = self.transform()
            if records > 0 and valid_count == 0:
                logger.error(
                    "FATAL: Extracted %d records but 0 survived transformation. "
                    "Schema contract violation — failing pipeline.", records
                )
                sys.exit(1)
            self.load()
            logger.info("=== Pipeline Execution Finished Successfully ===")
            return 0
        except SystemExit:
            raise
        except Exception as exc:
            logger.critical("Pipeline execution FAILED: %s", exc, exc_info=True)
            raise RuntimeError(f"Pipeline execution failed: {exc}") from exc


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Connector Pipeline Runner")
    parser.add_argument("--date", help="Execution date (YYYY-MM-DD)", default=None)
    args = parser.parse_args()

    try:
        runner = PipelineRunner(execution_date=args.date)
        exit_code = runner.run()
        if exit_code != 0:
            sys.exit(1)
        sys.exit(0)
    except SystemExit as se:
        sys.exit(se.code)
    except Exception as exc:
        logging.getLogger("postgres_to_bigquery").critical("Pipeline failed with unhandled error: %s", exc, exc_info=True)
        sys.exit(1)
