"""Standalone Connector Pipeline: cloudsql_postgres_to_bigquery_etl
Generated by SDLC Data Engineer Agent.
Architecture: Cloud SQL PostgreSQL -> Local Staging -> BigQuery
Zero-mock policy: executes real extraction and loading only.
"""
import os
import sys
import logging
import argparse
from datetime import datetime
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [%(name)s] %(message)s",
)
logger = logging.getLogger("cloudsql_postgres_to_bigquery_etl")


class PipelineRunner:
    def __init__(self, execution_date: str = None):
        self.execution_date = execution_date or datetime.utcnow().strftime("%Y-%m-%d")
        self.staging_dir = os.path.join("staging", "cloudsql_postgres_to_bigquery_etl", self.execution_date)
        os.makedirs(self.staging_dir, exist_ok=True)
        self.staging_file = os.path.join(self.staging_dir, "data.parquet")

    def extract(self) -> int:
        """Extracts data from real PostgreSQL into staging Parquet.
        
        Zero-mock policy: if credentials or sources are unavailable, raises an error immediately.
        """
        logger.info("Starting extraction from Cloud SQL PostgreSQL...")
        
        db_url = os.getenv("DATABASE_URL") or os.getenv("POSTGRES_URL")
        sql_engine = None
        sql_connector = None

        instance_connection_name = (
            os.getenv("INSTANCE_CONNECTION_NAME")
            or os.getenv("POSTGRES_INSTANCE_CONNECTION_NAME")
            or os.getenv("CLOUD_SQL_CONNECTION_NAME")
            or "upbeat-repeater-477110-q6:us-central1:sdlc-etl-demo-db"
        )
        host = os.getenv("POSTGRES_HOST") or os.getenv("DB_HOST", "")
        port = os.getenv("POSTGRES_PORT") or os.getenv("DB_PORT", "5432")
        user = os.getenv("POSTGRES_USER") or os.getenv("DB_USER", "559906504681-compute@developer")
        password = os.getenv("POSTGRES_PASSWORD") or os.getenv("DB_PASSWORD", "")
        dbname = os.getenv("POSTGRES_DB") or os.getenv("DB_NAME", "postgres")

        # Approach 1: Official Google Cloud SQL Python Connector (Connection Name + IAM auth / mTLS)
        if instance_connection_name and user:
            import sqlalchemy
            from google.cloud.sql.connector import Connector, IPTypes
            logger.info("Connecting via Google Cloud SQL Connector for %s", instance_connection_name)
            sql_connector = Connector()
            _is_iam = not bool(password)
            _ip_type = IPTypes.PRIVATE if (os.getenv("CLOUD_SQL_IP_TYPE", "PRIVATE").upper() == "PRIVATE") else IPTypes.PUBLIC
            
            def _getconn():
                return sql_connector.connect(
                    instance_connection_name,
                    "pg8000",
                    user=user,
                    password=password if password else None,
                    db=dbname,
                    enable_iam_auth=_is_iam,
                    ip_type=_ip_type,
                )
            sql_engine = sqlalchemy.create_engine("postgresql+pg8000://", creator=_getconn)
        elif db_url:
            import sqlalchemy
            sql_engine = sqlalchemy.create_engine(db_url)
        elif user and host and dbname:
            import sqlalchemy
            import urllib.parse
            _enc_pw = urllib.parse.quote_plus(password) if password else ""
            db_url_conn = f"postgresql://{user}:{_enc_pw}@{host}:{port}/{dbname}"
            sql_engine = sqlalchemy.create_engine(db_url_conn)
        else:
            raise EnvironmentError(
                "FATAL: Database connection parameters missing. Provide INSTANCE_CONNECTION_NAME, "
                "DATABASE_URL, or POSTGRES_* environment variables. Mock dummy data is disabled."
            )

        source_table = os.getenv("SOURCE_TABLE", "test_data")
        query = f"SELECT * FROM {source_table}"
        logger.info("Executing extraction query against PostgreSQL: %s", query)
        try:
            df = pd.read_sql(query, con=sql_engine)
        finally:
            if sql_engine is not None:
                sql_engine.dispose()
            if sql_connector is not None:
                sql_connector.close()

        row_count = len(df)
        df.to_parquet(self.staging_file, index=False)
        logger.info("Extracted %d records to %s", row_count, self.staging_file)
        return row_count

    def transform(self) -> int:
        """Schema-adaptive transformation with cleaning and type coercion.

        - Strips whitespace from text columns.
        - Sanitizes null values ('null', 'None', '', 'NaN').
        - Coerces types (numeric, boolean, timestamp).
        - Circuit breaker: if 100% of rows fail validation, exits with code 1.
        """
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file is empty. Nothing to transform.")
            return 0

        df = pd.read_parquet(self.staging_file)
        raw_count = len(df)
        if raw_count == 0:
            logger.warning("Staging DataFrame is empty. Nothing to transform.")
            return 0

        logger.info("Transforming %d raw records. Columns: %s", raw_count, list(df.columns))

        # 1. Clean string columns: trim whitespace and sanitize nulls
        for col in df.select_dtypes(include=["object", "string"]).columns:
            df[col] = df[col].astype(str).str.strip().replace({
                "nan": None, "NaN": None, "None": None, "none": None,
                "null": None, "NULL": None, "N/A": None, "n/a": None, "": None
            })

        # 2. Coerce known columns if present
        if "id" in df.columns:
            df["id"] = df["id"].astype(str)

        if "raw_text" in df.columns:
            df["raw_text"] = df["raw_text"].astype(str).str.strip().replace({"None": None, "nan": None, "": None})

        if "numeric_val" in df.columns:
            df["numeric_val"] = pd.to_numeric(df["numeric_val"], errors="coerce")

        if "is_active" in df.columns:
            def _to_bool(val):
                if pd.isna(val) or val is None:
                    return None
                s = str(val).strip().lower()
                if s in ["true", "1", "t", "yes", "y"]:
                    return True
                if s in ["false", "0", "f", "no", "n"]:
                    return False
                return None
            df["is_active"] = df["is_active"].apply(_to_bool)

        if "created_at" in df.columns:
            df["created_at"] = pd.to_datetime(df["created_at"], errors="coerce")

        # 3. Validity filter: drop rows where all columns are null
        df_valid = df.dropna(how="all")
        quarantined = raw_count - len(df_valid)
        if quarantined > 0:
            logger.warning("Quarantined %d fully-null records", quarantined)

        # 4. Circuit breaker
        if raw_count > 0 and len(df_valid) == 0:
            logger.error(
                "FATAL: 100%% of %d raw records were quarantined due to validation failure.",
                raw_count
            )
            sys.exit(1)

        # Overwrite staging file with cleaned data
        df_valid.to_parquet(self.staging_file, index=False)
        logger.info(
            "Transform complete: raw=%d, valid=%d, quarantined=%d",
            raw_count, len(df_valid), quarantined,
        )
        return len(df_valid)

    def load(self) -> bool:
        """Loads staged records into BigQuery destination.
        
        Zero-mock policy: if destination load fails, raises RuntimeError immediately.
        """
        logger.info("Loading staged file %s into BigQuery (analytics.postgres_test1)...", self.staging_file)
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file %s is empty or missing. Skipping load phase.", self.staging_file)
            return True

        project_id = os.getenv("GCP_PROJECT_ID") or os.getenv("PROJECT_ID") or os.getenv("GOOGLE_CLOUD_PROJECT") or "upbeat-repeater-477110-q6"
        dataset_id = os.getenv("BIGQUERY_DATASET") or "analytics"
        table_id = os.getenv("BIGQUERY_TABLE") or "postgres_test1"
        write_mode = os.getenv("WRITE_DISPOSITION", "WRITE_TRUNCATE").upper()

        if not project_id:
            raise EnvironmentError("FATAL: GCP_PROJECT_ID or PROJECT_ID must be set for BigQuery loading.")

        from google.cloud import bigquery
        client = bigquery.Client(project=project_id)
        table_ref = f"{project_id}.{dataset_id}.{table_id}"

        df = pd.read_parquet(self.staging_file)

        disposition = bigquery.WriteDisposition.WRITE_APPEND if write_mode in ["APPEND", "WRITE_APPEND"] else bigquery.WriteDisposition.WRITE_TRUNCATE
        job_config = bigquery.LoadJobConfig(
            write_disposition=disposition,
        )
        
        schema_file = os.path.join("schemas", "postgres_test1_schema.json")
        if os.path.isfile(schema_file):
            job_config.schema = client.schema_from_json(schema_file)
            logger.info("Attached explicit BigQuery schema from %s", schema_file)

        job = client.load_table_from_dataframe(df, table_ref, job_config=job_config)
        job.result()  # Blocks until BigQuery load completes

        if job.errors:
            raise RuntimeError(f"FATAL: BigQuery load job failed: {job.errors}")

        logger.info("Successfully loaded %d records into BigQuery table: %s", len(df), table_ref)
        return True

    def run(self) -> int:
        """Executes the end-to-end connector pipeline with fail-fast semantics."""
        logger.info("=== Starting Connector Pipeline Execution ===")
        try:
            records = self.extract()
            if records == 0:
                logger.warning("Extraction completed with 0 records.")
            valid_count = self.transform()
            if records > 0 and valid_count == 0:
                logger.error(
                    "FATAL: Extracted %d records but 0 survived transformation.", records
                )
                return 1
            self.load()
            logger.info("=== Pipeline Execution Finished Successfully ===")
            return 0
        except SystemExit:
            raise
        except Exception as exc:
            logger.critical("Pipeline execution FAILED: %s", exc, exc_info=True)
            raise


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Connector Pipeline Runner")
    parser.add_argument("--date", help="Execution date (YYYY-MM-DD)", default=None)
    args = parser.parse_args()

    try:
        runner = PipelineRunner(execution_date=args.date)
        exit_code = runner.run()
        if exit_code != 0:
            sys.exit(1)
        sys.exit(0)
    except Exception as exc:
        logger.critical("Pipeline failed with unhandled error: %s", exc, exc_info=True)
        sys.exit(1)
