"""Standalone Connector Pipeline: postgres_to_bigquery_test6
Generated by SDLC Data Engineer Agent.
Architecture: POSTGRESQL -> Local Staging -> BIGQUERY
Mock dummy data generation is completely disabled — real extraction & loading only.
"""
import os
import sys
import json
import logging
import argparse
from datetime import datetime

# Dependencies
try:
    import pandas as pd
except ImportError:
    pd = None

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except ImportError:
    pa = None
    pq = None

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [%(name)s] %(message)s",
)
logger = logging.getLogger("postgres_to_bigquery_test6")


class PipelineRunner:
    def __init__(self, execution_date: str = None):
        self.execution_date = execution_date or datetime.utcnow().strftime("%Y-%m-%d")
        self.staging_dir = os.path.join("staging", "postgres_to_bigquery_test6", self.execution_date)
        os.makedirs(self.staging_dir, exist_ok=True)
        self.staging_file = os.path.join(self.staging_dir, "data.parquet")

    def extract(self) -> int:
        """Extracts data from real postgresql into staging format.
        
        Zero-mock policy: if credentials or sources are unavailable, raises an error immediately.
        """
        logger.info("Starting real extraction from source: postgresql...")
        if pd is None:
            raise RuntimeError("FATAL: pandas is required for pipeline execution.")
        db_url = os.getenv("DATABASE_URL") or os.getenv("POSTGRES_URL")
        sql_engine = None
        sql_connector = None

        instance_connection_name = (
            os.getenv("INSTANCE_CONNECTION_NAME")
            or os.getenv("POSTGRES_INSTANCE_CONNECTION_NAME")
            or os.getenv("CLOUD_SQL_CONNECTION_NAME")
            or "upbeat-repeater-477110-q6:us-central1:sdlc-etl-demo-db"
        )
        host = os.getenv("POSTGRES_HOST") or os.getenv("DB_HOST", "")
        if not instance_connection_name and host and host.count(":") == 2:
            instance_connection_name = host
            host = ""

        port = os.getenv("POSTGRES_PORT") or os.getenv("DB_PORT", "5432")
        user = os.getenv("POSTGRES_USER") or os.getenv("DB_USER", "559906504681-compute@developer")
        dbname = os.getenv("POSTGRES_DB") or os.getenv("DB_NAME", "postgre")
        # NOTE: POSTGRES_PASSWORD is intentionally NOT read here.
        # All Cloud SQL connections use IAM database authentication.
        # A password would bypass IAM auth and fail anyway (no password set in DB).

        # Cloud SQL Python Connector with mandatory IAM Authentication
        if instance_connection_name and user:
            try:
                import sqlalchemy
                from google.cloud.sql.connector import Connector, IPTypes
                logger.info(
                    "Connecting via Cloud SQL Python Connector for %s (IAM auth, user=%s)",
                    instance_connection_name, user
                )
                sql_connector = Connector()
                _ip_type = IPTypes.PRIVATE if (os.getenv("CLOUD_SQL_IP_TYPE", "PRIVATE").upper() == "PRIVATE") else IPTypes.PUBLIC
                def _getconn():
                    return sql_connector.connect(
                        instance_connection_name,
                        "pg8000",
                        user=user,
                        db=dbname,
                        enable_iam_auth=True,  # ALWAYS True — IAM auth is mandatory
                        ip_type=_ip_type,
                    )
                sql_engine = sqlalchemy.create_engine("postgresql+pg8000://", creator=_getconn)
            except Exception as _conn_err:
                logger.error(
                    "FATAL: Cloud SQL Python Connector initialization failed: %s. "
                    "Ensure cloud-sql-python-connector is in requirements.txt and "
                    "INSTANCE_CONNECTION_NAME, POSTGRES_USER, POSTGRES_DB are set correctly.",
                    _conn_err
                )
                raise RuntimeError(f"Cloud SQL connector failed: {_conn_err}") from _conn_err

        con_target = sql_engine if sql_engine is not None else db_url
        if not con_target:
            raise EnvironmentError(
                "FATAL: Database connection parameters missing. "
                "Provide INSTANCE_CONNECTION_NAME + POSTGRES_USER + POSTGRES_DB for Cloud SQL IAM auth, "
                "or DATABASE_URL for direct connection. Mock dummy data is disabled."
            )

        query = "SELECT * FROM test_data"
        logger.info("Executing extraction query against PostgreSQL: %s", query)
        try:
            df = pd.read_sql(query, con=con_target)
        finally:
            if sql_engine is not None:
                sql_engine.dispose()
            if sql_connector is not None:
                sql_connector.close()

        row_count = len(df)
        df.to_parquet(self.staging_file, index=False)
        logger.info("Extracted %d real records to %s", row_count, self.staging_file)
        return row_count

    def transform(self) -> int:
        """Schema-adaptive transformation with flexible parsing.

        - Discovers columns dynamically from the extracted DataFrame.
        - Applies common column aliases.
        - Parses all date/timestamp columns flexibly.
        - Coerces numeric columns gracefully.
        - Circuit breaker: if 100% of rows fail validation, exits with code 1.
        """
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file is empty. Nothing to transform.")
            return 0

        df = pd.read_parquet(self.staging_file)
        raw_count = len(df)
        if raw_count == 0:
            logger.warning("Staging DataFrame is empty. Nothing to transform.")
            return 0

        logger.info("Transforming %d raw records. Columns: %s", raw_count, list(df.columns))

        # ── 1. Column name standardization & normalization helper ──
        import re
        _FOOTNOTE_RE = re.compile(r"\[[^\]]*\]")
        _NUMERIC_STRIP_RE = re.compile(r"[,$€£¥\s\u00a0]")

        def _normalize_numeric_series(series: pd.Series) -> pd.Series:
            """Strip footnote annotations, currency symbols, thousands separators, and
            whitespace so a column can be cast as numeric."""
            return (
                series.astype(str)
                .str.replace(_FOOTNOTE_RE, "", regex=True)
                .str.replace(_NUMERIC_STRIP_RE, "", regex=True)
                .str.strip()
            )

        df.columns = [
            re.sub(r"[^a-zA-Z0-9_]+", "_", str(col).strip().lower()).strip("_")
            for col in df.columns
        ]
        logger.info("Standardized columns: %s", list(df.columns))
        # ── 2. Specification-Driven Column Transformations ──────────
        if "id" in df.columns:
            df["id"] = _normalize_numeric_series(df["id"])
            df["id"] = pd.to_numeric(df["id"], errors="coerce").astype("Int64")
            logger.info("Applied specification transformation to id -> INTEGER")
        if "name" in df.columns:
            df["name"] = df["name"].astype(str).str.strip().replace({"nan": None, "None": None, "": None})
            logger.info("Applied specification transformation to name -> STRING")
        if "email" in df.columns:
            df["email"] = df["email"].astype(str).str.strip().replace({"nan": None, "None": None, "": None})
            logger.info("Applied specification transformation to email -> STRING")
        if "value" in df.columns:
            df["value"] = df["value"].astype(str).str.strip().replace({"nan": None, "None": None, "": None})
            logger.info("Applied specification transformation to value -> FLOAT64")
        if "created_at" in df.columns:
            df["created_at"] = pd.to_datetime(df["created_at"], errors="coerce")
            logger.info("Applied specification transformation to created_at -> TIMESTAMP")
        if "updated_at" in df.columns:
            df["updated_at"] = pd.to_datetime(df["updated_at"], errors="coerce")
            logger.info("Applied specification transformation to updated_at -> TIMESTAMP")

        # Standardize remaining string columns
        for col in df.select_dtypes(include=["object", "string"]).columns:
            df[col] = df[col].astype(str).str.strip().replace({"nan": None, "None": None, "": None})
        # ── 3. Basic validity filter (non-empty rows only) ─────────
        df_valid = df.dropna(how="all")
        quarantined = raw_count - len(df_valid)
        if quarantined > 0:
            logger.warning("Quarantined %d fully-null records", quarantined)

        # ── 4. Circuit breaker ─────────────────────────────────────
        if raw_count > 0 and len(df_valid) == 0:
            logger.error(
                "FATAL: 100%% of %d raw records were quarantined. "
                "This indicates a schema contract violation between "
                "the source data and the pipeline expectations. "
                "Failing the pipeline.", raw_count
            )
            sys.exit(1)

        # ── 5. Add ingestion audit timestamp ───────────────────────
        df_valid = df_valid.copy()
        df_valid["ingested_at"] = datetime.utcnow().isoformat()

        # Overwrite staging file with cleaned data
        df_valid.to_parquet(self.staging_file, index=False)
        logger.info(
            "Transform complete: raw=%d, valid=%d, quarantined=%d",
            raw_count, len(df_valid), quarantined,
        )
        return len(df_valid)

    def load(self) -> bool:
        """Loads staged records into real bigquery destination.
        
        Zero-mock policy: if destination load fails, raises RuntimeError immediately.
        """
        logger.info("Loading staged file %s into bigquery (analytics.test6)...", self.staging_file)
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file %s is empty or missing. Skipping load phase.", self.staging_file)
            return True
        project_id = os.getenv("GCP_PROJECT_ID") or os.getenv("PROJECT_ID") or os.getenv("GOOGLE_CLOUD_PROJECT") or os.getenv("GCLOUD_PROJECT") or "upbeat-repeater-477110-q6"
        dataset_id = os.getenv("BIGQUERY_DATASET") or "analytics"
        table_id = os.getenv("BIGQUERY_TABLE") or "test6"
        write_mode = "overwrite"

        if not project_id:
            raise EnvironmentError("FATAL: GCP_PROJECT_ID or PROJECT_ID must be set for BigQuery loading.")

        from google.cloud import bigquery
        client = bigquery.Client(project=project_id)
        table_ref = f"{project_id}.{dataset_id}.{table_id}"

        df = pd.read_parquet(self.staging_file)

        job_config = bigquery.LoadJobConfig(
            write_disposition=bigquery.WriteDisposition.WRITE_APPEND if write_mode == "append" else bigquery.WriteDisposition.WRITE_TRUNCATE,
        )
        schema_file = None
        for cand in [
            os.path.join("schemas", "test6_schema.json"),
            os.path.join("schemas", "postgres_to_bigquery_test6_schema.json"),
            os.path.join("schemas", "target_table_schema.json"),
        ]:
            if os.path.isfile(cand):
                schema_file = cand
                break
        if schema_file:
            try:
                job_config.schema = client.schema_from_json(schema_file)
                logger.info("Attached explicit BigQuery schema from %s", schema_file)
            except Exception as schema_err:
                logger.error("Could not parse schema from %s: %s", schema_file, schema_err)
                raise RuntimeError(f"Could not load schema from {schema_file}: {schema_err}") from schema_err
        if write_mode == "append":
            job_config.schema_update_options = [
                bigquery.SchemaUpdateOption.ALLOW_FIELD_ADDITION,
                bigquery.SchemaUpdateOption.ALLOW_FIELD_RELAXATION,
            ]
        job = client.load_table_from_dataframe(df, table_ref, job_config=job_config)
        job.result()  # Blocks until BigQuery load completes

        if job.errors:
            raise RuntimeError(f"FATAL: BigQuery load job failed: {job.errors}")

        logger.info("Successfully loaded %d records into BigQuery table: %s", len(df), table_ref)
        return True

    def run(self) -> int:
        """Executes the end-to-end connector pipeline with fail-fast semantics."""
        logger.info("=== Starting Connector Pipeline Execution ===")
        try:
            records = self.extract()
            if records == 0:
                logger.warning("Extraction completed with 0 records.")
            valid_count = self.transform()
            if records > 0 and valid_count == 0:
                logger.error(
                    "FATAL: Extracted %d records but 0 survived transformation. "
                    "Schema contract violation — failing pipeline.", records
                )
                sys.exit(1)
            self.load()
            logger.info("=== Pipeline Execution Finished Successfully ===")
            return 0
        except SystemExit:
            raise
        except Exception as exc:
            logger.critical("Pipeline execution FAILED: %s", exc, exc_info=True)
            raise RuntimeError(f"Pipeline execution FAILED: {exc}") from exc


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Connector Pipeline Runner")
    parser.add_argument("--date", help="Execution date (YYYY-MM-DD)", default=None)
    args = parser.parse_args()

    try:
        runner = PipelineRunner(execution_date=args.date)
        exit_code = runner.run()
        if exit_code != 0:
            sys.exit(1)
        sys.exit(0)
    except SystemExit:
        raise
    except Exception as exc:
        logging.getLogger("postgres_to_bigquery_test6").critical("Pipeline failed with unhandled error: %s", exc, exc_info=True)
        sys.exit(1)
