"""Standalone Connector Pipeline: sales_order_etl
Generated by SDLC Data Engineer Agent.
Architecture: GCS -> Local Staging -> BIGQUERY
Mock dummy data generation is completely disabled — real extraction & loading only.
"""
import os
import sys
import uuid
import json
import logging
import argparse
from datetime import datetime

try:
    import pandas as pd
except ImportError:
    pd = None

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except ImportError:
    pa = None
    pq = None

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [%(name)s] %(message)s",
)
logger = logging.getLogger("sales_order_etl")


class PipelineRunner:
    def __init__(self, execution_date: str = None):
        self.execution_date = execution_date or datetime.utcnow().strftime("%Y-%m-%d")
        self.staging_dir = os.path.join("staging", "sales_order_etl", self.execution_date)
        os.makedirs(self.staging_dir, exist_ok=True)
        self.staging_file = os.path.join(self.staging_dir, "data.parquet")
        self.batch_id = str(uuid.uuid4())
        self.source_bucket = os.getenv("GCS_SOURCE_BUCKET") or "sdlc-workspec-store"
        self.source_prefix = os.getenv("GCS_SOURCE_PREFIX") or "etl/data/raw_sales_data.csv"
        self.source_uri = f"gs://{self.source_bucket}/{self.source_prefix}"

    def extract(self) -> int:
        """Extracts data from real gcs into staging format.
        
        Zero-mock policy: if credentials or sources are unavailable, raises an error immediately.
        """
        logger.info("Starting real extraction from source: gcs...")
        if pd is None:
            raise RuntimeError("FATAL: pandas is required for pipeline execution.")
        from google.cloud import storage

        if not self.source_bucket:
            raise EnvironmentError("FATAL: GCS source bucket not configured. Set GCS_SOURCE_BUCKET.")

        logger.info("Extracting real data from GCS bucket: %s", self.source_uri)
        client = storage.Client()
        bucket = client.bucket(self.source_bucket)
        blobs = [b for b in bucket.list_blobs(prefix=self.source_prefix) if not b.name.endswith("/")]
        if not blobs:
            raise FileNotFoundError(f"FATAL: No data files found in {self.source_uri}. Mock fallback disabled.")

        dfs = []
        for blob in blobs:
            local_path = os.path.join(self.staging_dir, os.path.basename(blob.name))
            blob.download_to_filename(local_path)
            if local_path.endswith(".parquet"):
                dfs.append(pd.read_parquet(local_path))
            elif local_path.endswith(".csv"):
                dfs.append(pd.read_csv(local_path))
            elif local_path.endswith(".json") or local_path.endswith(".jsonl"):
                dfs.append(pd.read_json(local_path, lines=True))

        if not dfs:
            raise FileNotFoundError(f"FATAL: No parseable data files found in {self.source_uri}")

        df = pd.concat(dfs, ignore_index=True)
        row_count = len(df)
        df.to_parquet(self.staging_file, index=False)
        logger.info("Extracted %d real records from GCS to %s", row_count, self.staging_file)
        return row_count

    def transform(self) -> int:
        """Schema-adaptive transformation with cleaning and deduplication.

        - Cleans strings, trims whitespace.
        - Coerces types (amounts, created_at, order_id).
        - Deduplicates by order_id keeping latest created_at.
        - Adds audit columns: _etl_ingested_at, _etl_batch_id, _etl_source_file.
        - Circuit breaker: if 100% of rows fail validation, exits with code 1.
        """
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file is empty. Nothing to transform.")
            return 0

        df = pd.read_parquet(self.staging_file)
        raw_count = len(df)
        if raw_count == 0:
            logger.warning("Staging DataFrame is empty. Nothing to transform.")
            return 0

        logger.info("Transforming %d raw records. Columns: %s", raw_count, list(df.columns))

        # 1. Standardize column names to snake_case
        import re
        df.columns = [
            re.sub(r"[^a-zA-Z0-9_]+", "_", str(col).strip().lower()).strip("_")
            for col in df.columns
        ]

        # 2. Field-level cleansing and type enforcement
        if "order_id" in df.columns:
            df["order_id"] = pd.to_numeric(df["order_id"], errors="coerce").astype("Int64")

        if "amount" in df.columns:
            df["amount"] = pd.to_numeric(
                df["amount"].astype(str).str.replace(r"[,$€£¥\s]", "", regex=True),
                errors="coerce"
            ).astype("float64")

        if "created_at" in df.columns:
            df["created_at"] = pd.to_datetime(df["created_at"], errors="coerce", utc=True)

        # Clean string columns
        for col in ["customer_id", "customer_name", "product_category", "currency", "order_status"]:
            if col in df.columns:
                df[col] = df[col].astype(str).str.strip()
                df[col] = df[col].replace({"nan": None, "None": None, "": None})

        if "customer_email" in df.columns:
            df["customer_email"] = df["customer_email"].astype(str).str.strip().str.lower()
            df["customer_email"] = df["customer_email"].replace({"nan": None, "none": None, "": None})

        # 3. Validity filter: Drop completely empty rows or rows missing critical keys
        if "order_id" in df.columns:
            df_valid = df[df["order_id"].notna()].copy()
        else:
            df_valid = df.dropna(how="all").copy()

        quarantined = raw_count - len(df_valid)
        if quarantined > 0:
            logger.warning("Quarantined %d invalid records", quarantined)

        # 4. Circuit breaker
        if raw_count > 0 and len(df_valid) == 0:
            logger.error(
                "FATAL: 100%% of %d raw records were quarantined. Circuit breaker triggered.",
                raw_count
            )
            sys.exit(1)

        # 5. Deduplication: deduplicate on order_id, keeping the latest created_at
        if "order_id" in df_valid.columns:
            if "created_at" in df_valid.columns:
                df_valid = df_valid.sort_values(by="created_at", ascending=False)
            initial_count = len(df_valid)
            df_valid = df_valid.drop_duplicates(subset=["order_id"], keep="first").copy()
            dedup_removed = initial_count - len(df_valid)
            logger.info("Deduplication removed %d duplicate records by order_id", dedup_removed)

        # 6. Audit columns
        now_utc = datetime.utcnow()
        df_valid["_etl_ingested_at"] = pd.to_datetime(now_utc, utc=True)
        df_valid["_etl_batch_id"] = self.batch_id
        df_valid["_etl_source_file"] = self.source_uri

        # Overwrite staging file with cleaned data
        df_valid.to_parquet(self.staging_file, index=False)
        logger.info(
            "Transform complete: raw=%d, valid=%d, quarantined=%d",
            raw_count, len(df_valid), quarantined,
        )
        return len(df_valid)

    def load(self) -> bool:
        """Loads staged records into real bigquery destination.
        
        Zero-mock policy: if destination load fails, raises RuntimeError immediately.
        """
        logger.info("Loading staged file %s into bigquery (analytics.vishesh-test1)...", self.staging_file)
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file %s is empty or missing. Skipping load phase.", self.staging_file)
            return True
        project_id = os.getenv("GCP_PROJECT_ID") or os.getenv("PROJECT_ID") or os.getenv("GOOGLE_CLOUD_PROJECT") or os.getenv("GCLOUD_PROJECT")
        dataset_id = os.getenv("BIGQUERY_DATASET") or "analytics"
        table_id = os.getenv("BIGQUERY_TABLE") or "vishesh-test1"
        write_mode = "append"

        if not project_id:
            raise EnvironmentError("FATAL: GCP_PROJECT_ID or PROJECT_ID must be set for BigQuery loading.")

        from google.cloud import bigquery
        client = bigquery.Client(project=project_id)
        table_ref = f"{project_id}.{dataset_id}.{table_id}"

        df = pd.read_parquet(self.staging_file)

        job_config = bigquery.LoadJobConfig(
            write_disposition=bigquery.WriteDisposition.WRITE_APPEND if write_mode == "append" else bigquery.WriteDisposition.WRITE_TRUNCATE,
        )
        schema_file = None
        for cand in [
            os.path.join("schemas", f"{table_id}_schema.json"),
            os.path.join("schemas", "vishesh-test1_schema.json"),
            os.path.join("schemas", "sales_order_etl_schema.json"),
            os.path.join("schemas", "target_table_schema.json"),
        ]:
            if os.path.isfile(cand):
                schema_file = cand
                break
        if schema_file:
            job_config.schema = client.schema_from_json(schema_file)
            logger.info("Attached explicit BigQuery schema from %s", schema_file)

        if write_mode == "append":
            job_config.schema_update_options = [
                bigquery.SchemaUpdateOption.ALLOW_FIELD_ADDITION,
                bigquery.SchemaUpdateOption.ALLOW_FIELD_RELAXATION,
            ]
        job = client.load_table_from_dataframe(df, table_ref, job_config=job_config)
        job.result()

        if job.errors:
            raise RuntimeError(f"FATAL: BigQuery load job failed: {job.errors}")

        logger.info("Successfully loaded %d records into BigQuery table: %s", len(df), table_ref)
        return True

    def run(self) -> int:
        """Executes the end-to-end connector pipeline with fail-fast semantics."""
        logger.info("=== Starting Connector Pipeline Execution ===")
        try:
            records = self.extract()
            if records == 0:
                logger.warning("Extraction completed with 0 records.")
            valid_count = self.transform()
            if records > 0 and valid_count == 0:
                logger.error(
                    "FATAL: Extracted %d records but 0 survived transformation. "
                    "Schema contract violation — failing pipeline.", records
                )
                sys.exit(1)
            self.load()
            logger.info("=== Pipeline Execution Finished Successfully ===")
            return 0
        except SystemExit:
            raise
        except Exception as exc:
            logger.critical("Pipeline execution FAILED: %s", exc, exc_info=True)
            raise


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Connector Pipeline Runner")
    parser.add_argument("--date", help="Execution date (YYYY-MM-DD)", default=None)
    args = parser.parse_args()

    try:
        runner = PipelineRunner(execution_date=args.date)
        exit_code = runner.run()
        if exit_code != 0:
            sys.exit(1)
        sys.exit(0)
    except SystemExit as se:
        sys.exit(se.code)
    except Exception as exc:
        logger.critical("Pipeline failed with unhandled error: %s", exc, exc_info=True)
        sys.exit(1)
