"""Standalone Connector Pipeline: gcs_to_bq_test1
Generated by SDLC Data Engineer Agent.
Architecture: GCS -> Local Staging -> BIGQUERY
Mock dummy data generation is completely disabled — real extraction & loading only.
"""
import os
import sys
import json
import logging
import argparse
from datetime import datetime

# Dependencies
try:
    import pandas as pd
except ImportError:
    pd = None

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except ImportError:
    pa = None
    pq = None

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [%(name)s] %(message)s",
)
logger = logging.getLogger("gcs_to_bq_test1")


class PipelineRunner:
    def __init__(self, execution_date: str = None):
        self.execution_date = execution_date or datetime.utcnow().strftime("%Y-%m-%d")
        self.staging_dir = os.path.join("staging", "gcs_to_bq_test1", self.execution_date)
        os.makedirs(self.staging_dir, exist_ok=True)
        self.staging_file = os.path.join(self.staging_dir, "data.parquet")

    def extract(self) -> int:
        """Extracts data from real gcs into staging format.
        
        Zero-mock policy: if credentials or sources are unavailable, raises an error immediately.
        """
        logger.info("Starting real extraction from source: gcs...")
        if pd is None:
            raise RuntimeError("FATAL: pandas is required for pipeline execution.")
        from google.cloud import storage
        bucket_name = os.getenv("GCS_SOURCE_BUCKET") or "sdlc-workspec-store"
        prefix = os.getenv("GCS_SOURCE_PREFIX") or "etl/data/my_file (1).csv"
        if not bucket_name:
            raise EnvironmentError("FATAL: GCS source bucket not configured. Set GCS_SOURCE_BUCKET.")

        logger.info("Extracting real data from GCS bucket: gs://%s/%s", bucket_name, prefix)
        client = storage.Client()
        bucket = client.bucket(bucket_name)
        blobs = [b for b in bucket.list_blobs(prefix=prefix) if not b.name.endswith("/")]
        if not blobs:
            raise FileNotFoundError(f"FATAL: No data files found in gs://{bucket_name}/{prefix}. Mock fallback disabled.")

        dfs = []
        for blob in blobs:
            local_path = os.path.join(self.staging_dir, os.path.basename(blob.name))
            blob.download_to_filename(local_path)
            if local_path.endswith(".parquet"):
                dfs.append(pd.read_parquet(local_path))
            elif local_path.endswith(".csv"):
                dfs.append(pd.read_csv(local_path))
            elif local_path.endswith(".json") or local_path.endswith(".jsonl"):
                dfs.append(pd.read_json(local_path, lines=True))

        if not dfs:
            raise FileNotFoundError(f"FATAL: No parseable data files found in gs://{bucket_name}/{prefix}")

        df = pd.concat(dfs, ignore_index=True)
        row_count = len(df)
        df.to_parquet(self.staging_file, index=False)
        logger.info("Extracted %d real records from GCS to %s", row_count, self.staging_file)
        return row_count

    def transform(self) -> int:
        """Schema-adaptive transformation with flexible parsing.

        - Discovers columns dynamically from the extracted DataFrame.
        - Applies common column aliases (e.g. created_at -> order_date).
        - Parses all date/timestamp columns flexibly (no hardcoded format strings).
        - Coerces numeric columns gracefully.
        - Circuit breaker: if 100% of rows fail validation, exits with code 1.
        """
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file is empty. Nothing to transform.")
            return 0

        df = pd.read_parquet(self.staging_file)
        raw_count = len(df)
        if raw_count == 0:
            logger.warning("Staging DataFrame is empty. Nothing to transform.")
            return 0

        logger.info("Transforming %d raw records. Columns: %s", raw_count, list(df.columns))

        # ── 1. Column name standardization & normalization helper ──
        import re
        _FOOTNOTE_RE = re.compile(r"\[[^\]]*\]")
        _NUMERIC_STRIP_RE = re.compile(r"[,$€£¥\s]")

        def _normalize_numeric_series(series: pd.Series) -> pd.Series:
            """Strip footnote annotations, currency symbols, thousands separators, and
            whitespace so a column can be cast as numeric."""
            return (
                series.astype(str)
                .str.replace(_FOOTNOTE_RE, "", regex=True)
                .str.replace(_NUMERIC_STRIP_RE, "", regex=True)
                .str.strip()
            )

        df.columns = [
            re.sub(r"[^a-zA-Z0-9_]+", "_", str(col).strip().lower()).strip("_")
            for col in df.columns
        ]
        logger.info("Standardized columns: %s", list(df.columns))
        # ── 2. Fallback transformations (with format normalization) ──
        # Date / Timestamp auto-detection
        for col in df.columns:
            if df[col].dtype == "object":
                sample = df[col].dropna().head(5)
                if not sample.empty:
                    parsed = pd.to_datetime(sample, errors="coerce")
                    if parsed.notna().sum() >= max(1, len(sample) * 0.6):
                        df[col] = pd.to_datetime(df[col], errors="coerce")
                        logger.info("Auto-parsed column %s as TIMESTAMP", col)

        # Numeric auto-detection with currency and footnote normalization
        for col in df.columns:
            if df[col].dtype == "object":
                sample = df[col].dropna().head(10)
                if not sample.empty:
                    cleaned_sample = _normalize_numeric_series(sample)
                    coerced = pd.to_numeric(cleaned_sample, errors="coerce")
                    if coerced.notna().sum() >= max(1, len(sample) * 0.8):
                        df[col] = pd.to_numeric(_normalize_numeric_series(df[col]), errors="coerce")
                        logger.info("Auto-coerced column %s to numeric (with format normalization)", col)

        for col in df.select_dtypes(include="object").columns:
            df[col] = df[col].astype(str).str.strip()
            df[col] = df[col].replace({"nan": None, "None": None, "": None})
        # ── 3. Basic validity filter (non-empty rows only) ─────────
        # Drop rows where ALL columns are null
        df_valid = df.dropna(how="all")
        quarantined = raw_count - len(df_valid)
        if quarantined > 0:
            logger.warning("Quarantined %d fully-null records", quarantined)

        # ── 4. Circuit breaker ─────────────────────────────────────
        if raw_count > 0 and len(df_valid) == 0:
            logger.error(
                "FATAL: 100%% of %d raw records were quarantined. "
                "This indicates a schema contract violation between "
                "the source data and the pipeline expectations. "
                "Failing the pipeline.", raw_count
            )
            raise RuntimeError(f"FATAL: All {raw_count} raw records were quarantined.")

        # ── 5. Add ingestion audit timestamp ───────────────────────
        df_valid = df_valid.copy()
        df_valid["ingested_at"] = datetime.utcnow().isoformat()

        # Overwrite staging file with cleaned data
        df_valid.to_parquet(self.staging_file, index=False)
        logger.info(
            "Transform complete: raw=%d, valid=%d, quarantined=%d",
            raw_count, len(df_valid), quarantined,
        )
        return len(df_valid)

    def load(self) -> bool:
        """Loads staged records into real bigquery destination.
        
        Zero-mock policy: if destination load fails, raises RuntimeError immediately.
        """
        logger.info("Loading staged file %s into bigquery (analytics.test1)...", self.staging_file)
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file %s is empty or missing. Skipping load phase.", self.staging_file)
            return True
        project_id = os.getenv("GCP_PROJECT_ID") or os.getenv("PROJECT_ID")
        dataset_id = "analytics"
        table_id = "test1"
        write_mode = "overwrite"

        if not project_id:
            raise EnvironmentError("FATAL: GCP_PROJECT_ID or PROJECT_ID must be set for BigQuery loading.")

        from google.cloud import bigquery
        client = bigquery.Client(project=project_id)
        table_ref = f"{project_id}.{dataset_id}.{table_id}"

        # Read staging Parquet back as DataFrame for type-safe loading.
        # Using load_table_from_dataframe instead of load_table_from_file
        # avoids the Parquet byte-width mismatch when the target table uses
        # NUMERIC (16 bytes) but the DataFrame has float64 (8 bytes).
        # Error avoided: "Got bytestring of length 8 (expected 16)"
        df = pd.read_parquet(self.staging_file)

        # NOTE: schema_update_options (ALLOW_FIELD_ADDITION, ALLOW_FIELD_RELAXATION) should ONLY
        # be specified with WRITE_APPEND, or with WRITE_TRUNCATE on an explicitly partitioned table.
        # Once an explicit schema is passed, BigQuery API rejects schema_update_options on WRITE_TRUNCATE with 400 INVALID_ARGUMENT.
        job_config = bigquery.LoadJobConfig(
            write_disposition=bigquery.WriteDisposition.WRITE_APPEND if write_mode == "append" else bigquery.WriteDisposition.WRITE_TRUNCATE,
        )
        if write_mode == "append":
            job_config.schema_update_options = [
                bigquery.SchemaUpdateOption.ALLOW_FIELD_ADDITION,
                bigquery.SchemaUpdateOption.ALLOW_FIELD_RELAXATION,
            ]
        job = client.load_table_from_dataframe(df, table_ref, job_config=job_config)
        job.result()  # Blocks until BigQuery load completes

        if job.errors:
            raise RuntimeError(f"FATAL: BigQuery load job failed: {job.errors}")

        logger.info("Successfully loaded %d records into BigQuery table: %s", len(df), table_ref)
        return True

    def run(self) -> int:
        """Executes the end-to-end connector pipeline with fail-fast semantics."""
        logger.info("=== Starting Connector Pipeline Execution ===")
        try:
            records = self.extract()
            if records == 0:
                logger.warning("Extraction completed with 0 records.")
            valid_count = self.transform()
            if records > 0 and valid_count == 0:
                logger.error(
                    "FATAL: Extracted %d records but 0 survived transformation. "
                    "Schema contract violation — failing pipeline.", records
                )
                raise RuntimeError(f"Extracted {records} records but 0 survived transformation.")
            self.load()
            logger.info("=== Pipeline Execution Finished Successfully ===")
            return 0
        except Exception as exc:
            logger.critical("Pipeline execution FAILED: %s", exc, exc_info=True)
            raise


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Connector Pipeline Runner")
    parser.add_argument("--date", help="Execution date (YYYY-MM-DD)", default=None)
    args = parser.parse_args()

    try:
        runner = PipelineRunner(execution_date=args.date)
        exit_code = runner.run()
        if exit_code != 0:
            sys.exit(exit_code)
        sys.exit(0)
    except Exception as exc:
        logging.getLogger("gcs_to_bq_test1").critical("Pipeline failed with unhandled error: %s", exc, exc_info=True)
        sys.exit(1)
