"""Standalone Connector Pipeline: postgres_to_bigquery_etl
Generated by SDLC Data Engineer Agent.
Architecture: POSTGRESQL -> Local Staging -> BIGQUERY
Mock dummy data generation is completely disabled — real extraction & loading only.
"""
import os
import sys
import json
import logging
import argparse
import re
from datetime import datetime

# Safe imports for optional dependencies
try:
    import pandas as pd
except (ImportError, Exception):
    pd = None

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except (ImportError, Exception):
    pa = None
    pq = None

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [%(name)s] %(message)s",
)
logger = logging.getLogger("postgres_to_bigquery_etl")


def _clean_str(val):
    """Normalizes string values, trims whitespace, and converts null sentinels to None."""
    if val is None:
        return None
    if isinstance(val, float) and val != val:
        return None
    s = str(val).strip()
    if s.lower() in ("nan", "none", "null", "n/a", "<na>", ""):
        return None
    return s


def _parse_timestamp(val):
    """Parses timestamp strings into ISO format or None."""
    if val is None:
        return None
    if isinstance(val, float) and val != val:
        return None
    if hasattr(val, "isoformat"):
        return val.isoformat()
    s = _clean_str(val)
    if s is None:
        return None
    for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%dT%H:%M:%S", "%Y-%m-%d %H:%M:%S.%f", "%Y-%m-%d"):
        try:
            dt = datetime.strptime(s, fmt)
            return dt.isoformat()
        except ValueError:
            continue
    return None


def transform_record(row: dict) -> dict:
    """Transforms a single record dict according to data cleaning specifications."""
    if not isinstance(row, dict):
        return {}
    cleaned = {}
    for k, v in row.items():
        std_key = re.sub(r"[^a-zA-Z0-9_]+", "_", str(k).strip().lower()).strip("_")
        if std_key in ("id", "category", "status", "data_payload"):
            cleaned[std_key] = _clean_str(v)
        elif std_key in ("created_at", "updated_at"):
            cleaned[std_key] = _parse_timestamp(v)
        else:
            if isinstance(v, str):
                cleaned[std_key] = _clean_str(v)
            else:
                cleaned[std_key] = v
    return cleaned


def transform_records(records: list) -> list:
    """Cleans a list of dict records, handles deduplication, and adds ingestion audit timestamp."""
    if not records:
        return []
    cleaned_records = []
    seen_ids = set()

    for rec in records:
        cleaned_rec = transform_record(rec)
        if any(v is not None for v in cleaned_rec.values()):
            cleaned_records.append(cleaned_rec)

    deduped = []
    for rec in reversed(cleaned_records):
        rec_id = rec.get("id")
        if rec_id is not None:
            if rec_id not in seen_ids:
                seen_ids.add(rec_id)
                deduped.append(rec)
        else:
            deduped.append(rec)
    deduped.reverse()

    now_iso = datetime.utcnow().isoformat()
    for rec in deduped:
        rec["ingested_at"] = now_iso

    return deduped


class PipelineRunner:
    def __init__(self, execution_date: str = None):
        self.execution_date = execution_date or datetime.utcnow().strftime("%Y-%m-%d")
        self.staging_dir = os.path.join("staging", "postgres_to_bigquery_etl", self.execution_date)
        os.makedirs(self.staging_dir, exist_ok=True)
        self.staging_file = os.path.join(self.staging_dir, "data.parquet")

    def extract(self) -> int:
        """Extracts data from real postgresql into staging format.
        
        Zero-mock policy: if credentials or sources are unavailable, raises an error immediately.
        """
        logger.info("Starting real extraction from source: postgresql...")
        db_url = os.getenv("DATABASE_URL") or os.getenv("POSTGRES_URL")
        sql_engine = None
        sql_connector = None

        instance_connection_name = (
            os.getenv("INSTANCE_CONNECTION_NAME")
            or os.getenv("POSTGRES_INSTANCE_CONNECTION_NAME")
            or os.getenv("CLOUD_SQL_CONNECTION_NAME")
            or ""
        )
        host = os.getenv("POSTGRES_HOST") or os.getenv("DB_HOST", "")
        if not instance_connection_name and host and host.count(":") == 2:
            instance_connection_name = host
            host = ""

        port = os.getenv("POSTGRES_PORT") or os.getenv("DB_PORT", "5432")
        user = os.getenv("POSTGRES_USER") or os.getenv("DB_USER", "")
        dbname = os.getenv("POSTGRES_DB") or os.getenv("DB_NAME", "")

        # Cloud SQL Python Connector with mandatory IAM Authentication
        if instance_connection_name and user:
            try:
                import sqlalchemy
                from google.cloud.sql.connector import Connector, IPTypes
                logger.info(
                    "Connecting via Cloud SQL Python Connector for %s (IAM auth, user=%s)",
                    instance_connection_name, user
                )
                sql_connector = Connector()
                _ip_type = IPTypes.PRIVATE if (os.getenv("CLOUD_SQL_IP_TYPE", "PRIVATE").upper() == "PRIVATE") else IPTypes.PUBLIC
                def _getconn():
                    return sql_connector.connect(
                        instance_connection_name,
                        "pg8000",
                        user=user,
                        db=dbname,
                        enable_iam_auth=True,  # ALWAYS True — IAM auth is mandatory
                        ip_type=_ip_type,
                    )
                sql_engine = sqlalchemy.create_engine("postgresql+pg8000://", creator=_getconn)
            except Exception as _conn_err:
                logger.error(
                    "FATAL: Cloud SQL Python Connector initialization failed: %s. "
                    "Ensure cloud-sql-python-connector is in requirements.txt and "
                    "INSTANCE_CONNECTION_NAME, POSTGRES_USER, POSTGRES_DB are set correctly.",
                    _conn_err
                )
                raise RuntimeError(f"Cloud SQL connector failed: {_conn_err}") from _conn_err

        con_target = sql_engine if sql_engine is not None else db_url
        if not con_target:
            raise EnvironmentError(
                "FATAL: Database connection parameters missing. "
                "Provide INSTANCE_CONNECTION_NAME + POSTGRES_USER + POSTGRES_DB for Cloud SQL IAM auth, "
                "or DATABASE_URL for direct connection. Mock dummy data is disabled."
            )

        query = "SELECT * FROM test_data"
        logger.info("Executing extraction query against PostgreSQL: %s", query)
        try:
            if pd is not None:
                df = pd.read_sql(query, con=con_target)
                row_count = len(df)
                df.to_parquet(self.staging_file, index=False)
            else:
                import sqlalchemy
                if not isinstance(con_target, sqlalchemy.engine.Engine):
                    con_target = sqlalchemy.create_engine(con_target)
                with con_target.connect() as conn:
                    result = conn.execute(sqlalchemy.text(query))
                    rows = [dict(row._mapping) for row in result]
                row_count = len(rows)
                json_path = self.staging_file.replace(".parquet", ".json")
                with open(json_path, "w", encoding="utf-8") as f:
                    json.dump(rows, f, default=str)
                self.staging_file = json_path
        finally:
            if sql_engine is not None:
                sql_engine.dispose()
            if sql_connector is not None:
                sql_connector.close()

        logger.info("Extracted %d real records to %s", row_count, self.staging_file)
        return row_count

    def transform(self) -> int:
        """Schema-adaptive transformation with flexible parsing.

        - Discovers columns dynamically from the extracted data.
        - Parses all date/timestamp columns.
        - Trims whitespace and normalizes nulls.
        - Circuit breaker: if 100% of rows fail validation, exits with code 1.
        """
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file is empty. Nothing to transform.")
            return 0

        # Read records from staging (JSON or Parquet)
        if self.staging_file.endswith(".json"):
            with open(self.staging_file, "r", encoding="utf-8") as f:
                records = json.load(f)
        elif pd is not None and self.staging_file.endswith(".parquet"):
            df = pd.read_parquet(self.staging_file)
            records = df.to_dict(orient="records")
        else:
            with open(self.staging_file, "r", encoding="utf-8") as f:
                records = json.load(f)

        raw_count = len(records)
        if raw_count == 0:
            logger.warning("Staging DataFrame is empty. Nothing to transform.")
            return 0

        logger.info("Transforming %d raw records.", raw_count)
        cleaned = transform_records(records)
        quarantined = raw_count - len(cleaned)
        if quarantined > 0:
            logger.warning("Quarantined %d fully-null records", quarantined)

        # Circuit breaker
        if raw_count > 0 and len(cleaned) == 0:
            logger.error(
                "FATAL: 100%% of %d raw records were quarantined. "
                "This indicates a schema contract violation.", raw_count
            )
            sys.exit(1)

        # Write cleaned records back
        if self.staging_file.endswith(".parquet") and pd is not None:
            df_out = pd.DataFrame(cleaned)
            df_out.to_parquet(self.staging_file, index=False)
        else:
            json_path = self.staging_file if self.staging_file.endswith(".json") else self.staging_file.replace(".parquet", ".json")
            with open(json_path, "w", encoding="utf-8") as f:
                json.dump(cleaned, f, default=str)
            self.staging_file = json_path

        logger.info("Transform complete: raw=%d, valid=%d, quarantined=%d", raw_count, len(cleaned), quarantined)
        return len(cleaned)

    def load(self) -> bool:
        """Loads staged records into real bigquery destination.
        
        Zero-mock policy: if destination load fails, raises RuntimeError immediately.
        """
        logger.info("Loading staged file %s into bigquery (analytics.postgres_test5)...", self.staging_file)
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file %s is empty or missing. Skipping load phase.", self.staging_file)
            return True

        project_id = os.getenv("GCP_PROJECT_ID") or os.getenv("PROJECT_ID") or os.getenv("GOOGLE_CLOUD_PROJECT") or os.getenv("GCLOUD_PROJECT")
        dataset_id = os.getenv("BIGQUERY_DATASET") or "analytics"
        table_id = os.getenv("BIGQUERY_TABLE") or "postgres_test5"
        write_mode = "append"

        from google.cloud import bigquery
        from google.cloud.exceptions import NotFound

        try:
            client = bigquery.Client(project=project_id) if project_id else bigquery.Client()
            if not project_id and getattr(client, "project", None):
                project_id = client.project
        except Exception as client_init_err:
            raise EnvironmentError(
                f"FATAL: Unable to initialize BigQuery client (project_id='{project_id}'): {client_init_err}"
            ) from client_init_err

        table_ref = f"{project_id}.{dataset_id}.{table_id}" if project_id else f"{dataset_id}.{table_id}"

        dataset_ref = client.dataset(dataset_id, project=project_id)
        try:
            client.get_dataset(dataset_ref)
        except NotFound:
            ds = bigquery.Dataset(dataset_ref)
            ds.location = os.getenv("BQ_LOCATION", "us-central1")
            client.create_dataset(ds, exists_ok=True)
            logger.info("Ensured target BigQuery dataset '%s' exists.", dataset_ref)

        job_config = bigquery.LoadJobConfig(
            write_disposition=bigquery.WriteDisposition.WRITE_APPEND if write_mode == "append" else bigquery.WriteDisposition.WRITE_TRUNCATE,
            create_disposition=bigquery.CreateDisposition.CREATE_IF_NEEDED,
        )
        schema_file = None
        for cand in [
            os.path.join("schemas", "postgres_test5_schema.json"),
            os.path.join("schemas", "postgres_to_bigquery_etl_schema.json"),
            os.path.join("schemas", "target_table_schema.json"),
        ]:
            if os.path.isfile(cand):
                schema_file = cand
                break

        if schema_file:
            raw_schema = client.schema_from_json(schema_file)
            job_config.schema = raw_schema
            logger.info("Attached BigQuery schema from %s (%d fields)", schema_file, len(raw_schema))
        else:
            job_config.autodetect = True

        if write_mode == "append":
            job_config.schema_update_options = [
                bigquery.SchemaUpdateOption.ALLOW_FIELD_ADDITION,
                bigquery.SchemaUpdateOption.ALLOW_FIELD_RELAXATION,
            ]

        if self.staging_file.endswith(".parquet") and pd is not None:
            df = pd.read_parquet(self.staging_file)
            if schema_file and job_config.schema:
                reconciled_schema = []
                for field in job_config.schema:
                    if field.name not in df.columns:
                        df[field.name] = None
                        reconciled_schema.append(bigquery.SchemaField(field.name, field.field_type, mode="NULLABLE"))
                    else:
                        reconciled_schema.append(field)
                for col in df.columns:
                    if col not in {sf.name for sf in reconciled_schema}:
                        reconciled_schema.append(bigquery.SchemaField(col, "STRING", mode="NULLABLE"))
                job_config.schema = reconciled_schema

                for field in reconciled_schema:
                    col = field.name
                    f_type = field.field_type.upper()
                    if col in df.columns:
                        try:
                            if f_type in ("INTEGER", "INT64"):
                                df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")
                            elif f_type in ("FLOAT", "FLOAT64", "NUMERIC", "BIGNUMERIC"):
                                df[col] = pd.to_numeric(df[col], errors="coerce")
                            elif f_type in ("TIMESTAMP", "DATETIME"):
                                df[col] = pd.to_datetime(df[col], errors="coerce", utc=True)
                            elif f_type in ("BOOLEAN", "BOOL"):
                                df[col] = df[col].map(
                                    lambda v: True if str(v).strip().lower() in ("true", "1", "t", "yes")
                                    else (False if str(v).strip().lower() in ("false", "0", "f", "no") else None)
                                    if pd.notna(v) else None
                                ).astype("boolean")
                            elif f_type == "STRING":
                                df[col] = df[col].apply(lambda v: str(v) if pd.notna(v) else None)
                        except (ValueError, TypeError, KeyError) as cast_err:
                            logger.warning("Type casting warning for column '%s' (%s): %s", col, f_type, cast_err)

            try:
                job = client.load_table_from_dataframe(df, table_ref, job_config=job_config)
                job.result()
            except Exception as load_err:
                logger.error("Primary load_table_from_dataframe failed: %s", load_err)
                raise RuntimeError(f"BigQuery load failed: {load_err}") from load_err

            logger.info("Successfully loaded %d records into BigQuery table: %s", len(df), table_ref)
        else:
            job_config.source_format = bigquery.SourceFormat.NEWLINE_DELIMITED_JSON
            json_file = self.staging_file if self.staging_file.endswith(".json") else self.staging_file.replace(".parquet", ".json")
            with open(json_file, "r", encoding="utf-8") as f:
                records = json.load(f)
            ndjson_path = json_file + ".ndjson"
            with open(ndjson_path, "w", encoding="utf-8") as f:
                for rec in records:
                    f.write(json.dumps(rec, default=str) + "\n")
            try:
                with open(ndjson_path, "rb") as source_file:
                    job = client.load_table_from_file(source_file, table_ref, job_config=job_config)
                    job.result()
            except Exception as load_err:
                logger.error("load_table_from_file failed: %s", load_err)
                raise RuntimeError(f"BigQuery load failed: {load_err}") from load_err
            finally:
                if os.path.exists(ndjson_path):
                    os.remove(ndjson_path)
            logger.info("Successfully loaded %d records from JSON into BigQuery table: %s", len(records), table_ref)
        return True

    def run(self) -> int:
        """Executes the end-to-end connector pipeline with fail-fast semantics."""
        logger.info("=== Starting Connector Pipeline Execution ===")
        try:
            records = self.extract()
            if records == 0:
                logger.warning("Extraction completed with 0 records.")
            valid_count = self.transform()
            if records > 0 and valid_count == 0:
                logger.error(
                    "FATAL: Extracted %d records but 0 survived transformation. "
                    "Schema contract violation — failing pipeline.", records
                )
                return 1
            self.load()
            logger.info("=== Pipeline Execution Finished Successfully ===")
            return 0
        except SystemExit:
            raise
        except Exception as exc:
            logger.critical("Pipeline execution FAILED: %s", exc, exc_info=True)
            raise RuntimeError(f"Pipeline execution failed: {exc}") from exc


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Connector Pipeline Runner")
    parser.add_argument("--date", help="Execution date (YYYY-MM-DD)", default=None)
    args = parser.parse_args()

    runner = PipelineRunner(execution_date=args.date)
    exit_code = runner.run()
    if exit_code != 0:
        sys.exit(1)
    sys.exit(0)
