"""Standalone Connector Pipeline: gcs_sales_to_bigquery
Generated by SDLC Data Engineer Agent.
Architecture: GCS -> Local Staging -> BIGQUERY
Mock dummy data generation is completely disabled — real extraction & loading only.
"""
import os
import sys
import json
import logging
import argparse
import re
from datetime import datetime

try:
    import pandas as pd
except ImportError:
    pd = None

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except ImportError:
    pa = None
    pq = None

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [%(name)s] %(message)s",
)
logger = logging.getLogger("gcs_sales_to_bigquery")


class PipelineRunner:
    def __init__(self, execution_date: str = None):
        self.execution_date = execution_date or datetime.utcnow().strftime("%Y-%m-%d")
        self.staging_dir = os.path.join("staging", "gcs_sales_to_bigquery", self.execution_date)
        os.makedirs(self.staging_dir, exist_ok=True)
        self.staging_file = os.path.join(self.staging_dir, "data.parquet")

    def extract(self) -> int:
        """Extracts data from real GCS into staging format.
        
        Zero-mock policy: if credentials or sources are unavailable, raises an error immediately.
        """
        logger.info("Starting real extraction from source: gcs...")
        if pd is None:
            raise RuntimeError("FATAL: pandas is required for pipeline execution.")
        from google.cloud import storage
        bucket_name = os.getenv("GCS_SOURCE_BUCKET") or os.getenv("GCS_BUCKET_NAME") or "sdlc-workspec-store"
        prefix = os.getenv("GCS_SOURCE_PREFIX") or os.getenv("GCS_SOURCE_BLOB") or "etl/data/raw_sales_data.csv"
        if not bucket_name:
            raise EnvironmentError("FATAL: GCS source bucket not configured. Set GCS_SOURCE_BUCKET.")

        logger.info("Extracting real data from GCS bucket: gs://%s/%s", bucket_name, prefix)
        try:
            client = storage.Client()
            bucket = client.bucket(bucket_name)
            blobs = [b for b in bucket.list_blobs(prefix=prefix) if not b.name.endswith("/")]
        except Exception as exc:
            logger.critical("Failed to connect or list blobs in GCS bucket gs://%s/%s: %s", bucket_name, prefix, exc)
            raise

        if not blobs:
            raise FileNotFoundError(f"FATAL: No data files found in gs://{bucket_name}/{prefix}. Mock fallback disabled.")

        dfs = []
        for blob in blobs:
            local_path = os.path.join(self.staging_dir, os.path.basename(blob.name))
            try:
                blob.download_to_filename(local_path)
            except Exception as dl_err:
                logger.critical("Failed to download blob %s: %s", blob.name, dl_err)
                raise
            if local_path.endswith(".parquet"):
                dfs.append(pd.read_parquet(local_path))
            elif local_path.endswith(".csv"):
                dfs.append(pd.read_csv(local_path))
            elif local_path.endswith(".json") or local_path.endswith(".jsonl"):
                dfs.append(pd.read_json(local_path, lines=True))

        if not dfs:
            raise FileNotFoundError(f"FATAL: No parseable data files found in gs://{bucket_name}/{prefix}")

        df = pd.concat(dfs, ignore_index=True)
        row_count = len(df)
        df.to_parquet(self.staging_file, index=False)
        logger.info("Extracted %d real records from GCS to %s", row_count, self.staging_file)
        return row_count

    def transform(self) -> int:
        """Schema-adaptive transformation with cleaning and deduplication.

        - Standardizes column names.
        - Trims whitespace and normalizes empty strings to null.
        - Casts data types (INTEGER, FLOAT, TIMESTAMP, STRING).
        - Deduplicates records on business primary key (`order_id`), keeping the last record.
        - Circuit breaker: if 100% of rows fail validation, exits with code 1.
        """
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file is empty. Nothing to transform.")
            return 0

        df = pd.read_parquet(self.staging_file)
        raw_count = len(df)
        if raw_count == 0:
            logger.warning("Staging DataFrame is empty. Nothing to transform.")
            return 0

        logger.info("Transforming %d raw records. Columns: %s", raw_count, list(df.columns))

        _FOOTNOTE_RE = re.compile(r"\[[^\]]*\]")
        _NUMERIC_STRIP_RE = re.compile(r"[,$€£¥\s\u00a0]")

        def _normalize_numeric_series(series: pd.Series) -> pd.Series:
            return (
                series.astype(str)
                .str.replace(_FOOTNOTE_RE, "", regex=True)
                .str.replace(_NUMERIC_STRIP_RE, "", regex=True)
                .str.strip()
            )

        df.columns = [
            re.sub(r"[^a-zA-Z0-9_]+", "_", str(col).strip().lower()).strip("_")
            for col in df.columns
        ]
        logger.info("Standardized columns: %s", list(df.columns))

        # ── Column Transformations ──
        if "order_id" in df.columns:
            df["order_id"] = _normalize_numeric_series(df["order_id"])
            df["order_id"] = pd.to_numeric(df["order_id"], errors="coerce").astype("Int64")
            logger.info("Applied specification transformation to order_id -> INTEGER")

        if "customer_id" in df.columns:
            df["customer_id"] = df["customer_id"].astype(str).str.strip().replace({"nan": None, "None": None, "": None})
            logger.info("Applied specification transformation to customer_id -> STRING")

        if "customer_name" in df.columns:
            df["customer_name"] = df["customer_name"].astype(str).str.strip().replace({"nan": None, "None": None, "": None})
            logger.info("Applied specification transformation to customer_name -> STRING")

        if "customer_email" in df.columns:
            df["customer_email"] = df["customer_email"].astype(str).str.strip().replace({"nan": None, "None": None, "": None})
            logger.info("Applied specification transformation to customer_email -> STRING")

        if "product_category" in df.columns:
            df["product_category"] = df["product_category"].astype(str).str.strip().replace({"nan": None, "None": None, "": None})
            logger.info("Applied specification transformation to product_category -> STRING")

        if "amount" in df.columns:
            df["amount"] = _normalize_numeric_series(df["amount"])
            df["amount"] = pd.to_numeric(df["amount"], errors="coerce")
            logger.info("Applied specification transformation to amount -> FLOAT")

        if "currency" in df.columns:
            df["currency"] = df["currency"].astype(str).str.strip().replace({"nan": None, "None": None, "": None})
            logger.info("Applied specification transformation to currency -> STRING")

        if "order_status" in df.columns:
            df["order_status"] = df["order_status"].astype(str).str.strip().replace({"nan": None, "None": None, "": None})
            logger.info("Applied specification transformation to order_status -> STRING")

        if "created_at" in df.columns:
            df["created_at"] = pd.to_datetime(df["created_at"], errors="coerce", utc=True)
            logger.info("Applied specification transformation to created_at -> TIMESTAMP")

        for col in df.select_dtypes(include=["object", "string"]).columns:
            df[col] = df[col].astype(str).str.strip().replace({"nan": None, "None": None, "": None})

        # ── Deduplication on order_id ──
        if "order_id" in df.columns:
            initial_len = len(df)
            # Remove rows where order_id is null before deduplicating, or keep valid records
            df = df.drop_duplicates(subset=["order_id"], keep="last")
            duplicates_dropped = initial_len - len(df)
            logger.info("Deduplication complete: dropped %d duplicate records based on order_id", duplicates_dropped)

        # ── Validity filter (non-empty rows only) ──
        df_valid = df.dropna(how="all")
        quarantined = raw_count - len(df_valid)
        if quarantined > 0:
            logger.warning("Quarantined %d invalid or fully-null records", quarantined)

        # ── Circuit breaker ──
        if raw_count > 0 and len(df_valid) == 0:
            logger.critical(
                "FATAL: 100%% of %d raw records were quarantined. Schema contract violation.",
                raw_count
            )
            sys.exit(1)

        # ── Add ingestion audit timestamp ──
        df_valid = df_valid.copy()
        df_valid["ingested_at"] = datetime.utcnow().isoformat()

        df_valid.to_parquet(self.staging_file, index=False)
        logger.info(
            "Transform complete: raw=%d, valid=%d, quarantined=%d",
            raw_count, len(df_valid), quarantined,
        )
        return len(df_valid)

    def load(self) -> bool:
        """Loads staged records into BigQuery destination.
        
        Zero-mock policy: if destination load fails, raises RuntimeError immediately.
        """
        logger.info("Loading staged file %s into BigQuery...", self.staging_file)
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file %s is empty or missing. Skipping load phase.", self.staging_file)
            return True

        project_id = (
            os.getenv("GCP_PROJECT_ID")
            or os.getenv("PROJECT_ID")
            or os.getenv("GOOGLE_CLOUD_PROJECT")
            or os.getenv("GCLOUD_PROJECT")
            or "upbeat-repeater-477110-q6"
        )
        dataset_id = os.getenv("BQ_DATASET_ID") or os.getenv("BIGQUERY_DATASET") or "analytics"
        table_id = os.getenv("BQ_TABLE_ID") or os.getenv("BIGQUERY_TABLE") or "harshada-test4"
        write_mode = os.getenv("WRITE_MODE", "append").lower()

        from google.cloud import bigquery
        from google.api_core.exceptions import GoogleAPIError

        try:
            client = bigquery.Client(project=project_id)
        except Exception as client_init_err:
            logger.critical("FATAL: Unable to initialize BigQuery client: %s", client_init_err)
            raise EnvironmentError(f"BigQuery client initialization failed: {client_init_err}") from client_init_err

        table_ref = f"{project_id}.{dataset_id}.{table_id}"

        # Ensure dataset exists
        try:
            dataset_ref = bigquery.DatasetReference(project_id, dataset_id)
            ds = bigquery.Dataset(dataset_ref)
            ds.location = os.getenv("BQ_LOCATION", "us-central1")
            client.create_dataset(ds, exists_ok=True)
            logger.info("Target BigQuery dataset '%s' verified.", dataset_id)
        except GoogleAPIError as ds_err:
            logger.warning("Dataset pre-check notice for '%s': %s", dataset_id, ds_err)

        df = pd.read_parquet(self.staging_file)

        job_config = bigquery.LoadJobConfig(
            write_disposition=(
                bigquery.WriteDisposition.WRITE_APPEND
                if write_mode == "append"
                else bigquery.WriteDisposition.WRITE_TRUNCATE
            ),
            create_disposition=bigquery.CreateDisposition.CREATE_IF_NEEDED,
        )

        schema_file = None
        for cand in [
            os.path.join("schemas", f"{table_id}_schema.json"),
            os.path.join("schemas", "harshada-test4_schema.json"),
            os.path.join("schemas", "harshada_test4_schema.json"),
            os.path.join("schemas", "gcs_sales_to_bigquery_schema.json"),
            os.path.join("schemas", "target_table_schema.json"),
        ]:
            if os.path.isfile(cand):
                schema_file = cand
                break

        if schema_file:
            try:
                raw_schema = client.schema_from_json(schema_file)
                reconciled_schema = []
                for field in raw_schema:
                    if field.name not in df.columns:
                        df[field.name] = None
                        reconciled_schema.append(
                            bigquery.SchemaField(
                                name=field.name,
                                field_type=field.field_type,
                                mode="NULLABLE",
                                description=field.description,
                            )
                        )
                    else:
                        reconciled_schema.append(field)

                schema_col_names = {sf.name for sf in raw_schema}
                for col in df.columns:
                    if col not in schema_col_names:
                        reconciled_schema.append(
                            bigquery.SchemaField(
                                name=col,
                                field_type="STRING",
                                mode="NULLABLE",
                                description=f"Dynamically discovered column '{col}'",
                            )
                        )

                # Type-safe coercion
                for field in reconciled_schema:
                    col = field.name
                    f_type = field.field_type.upper()
                    if col in df.columns:
                        if f_type in ("INTEGER", "INT64"):
                            df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")
                        elif f_type in ("FLOAT", "FLOAT64", "NUMERIC", "BIGNUMERIC"):
                            df[col] = pd.to_numeric(df[col], errors="coerce")
                        elif f_type in ("TIMESTAMP", "DATETIME"):
                            df[col] = pd.to_datetime(df[col], errors="coerce", utc=True)
                        elif f_type in ("BOOLEAN", "BOOL"):
                            df[col] = df[col].map(
                                lambda v: True if str(v).strip().lower() in ("true", "1", "t", "yes")
                                else (False if str(v).strip().lower() in ("false", "0", "f", "no") else None)
                                if pd.notna(v) else None
                            ).astype("boolean")
                        elif f_type == "STRING":
                            df[col] = df[col].apply(lambda v: str(v) if pd.notna(v) else None)

                job_config.schema = reconciled_schema
                logger.info("Attached reconciled BigQuery schema from %s (%d fields)", schema_file, len(reconciled_schema))
            except (OSError, json.JSONDecodeError, ValueError) as schema_err:
                logger.warning("Could not attach schema from %s: %s; falling back to autodetect", schema_file, schema_err)
                job_config.autodetect = True
        else:
            job_config.autodetect = True

        if write_mode == "append":
            job_config.schema_update_options = [
                bigquery.SchemaUpdateOption.ALLOW_FIELD_ADDITION,
                bigquery.SchemaUpdateOption.ALLOW_FIELD_RELAXATION,
            ]

        try:
            job = client.load_table_from_dataframe(df, table_ref, job_config=job_config)
            job.result()
        except Exception as load_err:
            logger.critical("Failed to load DataFrame to BigQuery table %s: %s", table_ref, load_err)
            raise RuntimeError(f"BigQuery load failed: {load_err}") from load_err

        logger.info("Successfully loaded %d records into BigQuery table: %s", len(df), table_ref)
        return True

    def run(self) -> int:
        """Executes the end-to-end connector pipeline with fail-fast semantics."""
        logger.info("=== Starting Connector Pipeline Execution ===")
        try:
            records = self.extract()
            if records == 0:
                logger.warning("Extraction completed with 0 records.")
            valid_count = self.transform()
            if records > 0 and valid_count == 0:
                logger.critical(
                    "FATAL: Extracted %d records but 0 survived transformation. Failing pipeline.", records
                )
                return 1
            self.load()
            logger.info("=== Pipeline Execution Finished Successfully ===")
            return 0
        except SystemExit:
            raise
        except Exception as exc:
            logger.critical("Pipeline execution FAILED: %s", exc, exc_info=True)
            raise


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Connector Pipeline Runner")
    parser.add_argument("--date", help="Execution date (YYYY-MM-DD)", default=None)
    args = parser.parse_args()

    runner = PipelineRunner(execution_date=args.date)
    exit_code = runner.run()
    if exit_code != 0:
        sys.exit(1)
    sys.exit(0)
