"""Standalone Connector Pipeline: sales_etl
Generated by SDLC Data Engineer Agent for SCRUM-355.
Architecture: GCS -> Local Staging -> BigQuery
Mock dummy data generation is completely disabled — real extraction & loading only.
"""
import os
import sys
import json
import re
import logging
import argparse
from datetime import datetime
from typing import Optional

try:
    import pandas as pd
except ImportError:
    pd = None

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except ImportError:
    pa = None
    pq = None

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [%(name)s] %(message)s",
)
logger = logging.getLogger("sales_etl")


class PipelineRunner:
    """ETL Pipeline Runner for Sales Data: GCS -> BigQuery."""

    def __init__(self, execution_date: Optional[str] = None):
        self.execution_date = execution_date or datetime.utcnow().strftime("%Y-%m-%d")
        self.staging_dir = os.path.join("staging", "sales_etl", self.execution_date)
        os.makedirs(self.staging_dir, exist_ok=True)
        self.staging_file = os.path.join(self.staging_dir, "data.parquet")

    def extract(self) -> int:
        """Extracts raw sales CSV from Google Cloud Storage into local parquet staging.
        
        Zero-mock policy: if credentials or sources are unavailable, raises an error immediately.
        """
        logger.info("Starting extraction from source GCS...")
        if pd is None:
            raise RuntimeError("FATAL: pandas is required for pipeline execution.")

        gcs_source_url = os.getenv("GCS_SOURCE_URL") or "gs://sdlc-workspec-store/etl/data/raw_sales_data.csv"
        bucket_name = os.getenv("GCS_SOURCE_BUCKET")
        prefix = os.getenv("GCS_SOURCE_PREFIX")

        if not bucket_name or not prefix:
            if gcs_source_url.startswith("gs://"):
                parts = gcs_source_url[5:].split("/", 1)
                bucket_name = bucket_name or parts[0]
                prefix = prefix or (parts[1] if len(parts) > 1 else "")
            elif "storage.googleapis.com" in gcs_source_url:
                clean_url = gcs_source_url.split("storage.googleapis.com/")[-1]
                parts = clean_url.split("/", 1)
                bucket_name = bucket_name or parts[0]
                prefix = prefix or (parts[1] if len(parts) > 1 else "")
            else:
                bucket_name = bucket_name or "sdlc-workspec-store"
                prefix = prefix or "etl/data/raw_sales_data.csv"

        logger.info("Extracting data from GCS: gs://%s/%s", bucket_name, prefix)
        from google.cloud import storage

        client = storage.Client()
        bucket = client.bucket(bucket_name)

        blob = bucket.blob(prefix)
        blobs = []
        if blob.exists():
            blobs = [blob]
        else:
            blobs = [b for b in bucket.list_blobs(prefix=prefix) if not b.name.endswith("/")]

        if not blobs:
            raise FileNotFoundError(f"FATAL: No data files found in gs://{bucket_name}/{prefix}. Mock fallback disabled.")

        dfs = []
        for b in blobs:
            local_path = os.path.join(self.staging_dir, os.path.basename(b.name))
            b.download_to_filename(local_path)
            if local_path.endswith(".parquet"):
                dfs.append(pd.read_parquet(local_path))
            elif local_path.endswith(".csv"):
                dfs.append(pd.read_csv(local_path))
            elif local_path.endswith(".json") or local_path.endswith(".jsonl"):
                dfs.append(pd.read_json(local_path, lines=True))
            else:
                dfs.append(pd.read_csv(local_path))

        if not dfs:
            raise FileNotFoundError(f"FATAL: No parseable data files found in gs://{bucket_name}/{prefix}")

        df = pd.concat(dfs, ignore_index=True)
        row_count = len(df)
        df.to_parquet(self.staging_file, index=False)
        logger.info("Extracted %d records from GCS to %s", row_count, self.staging_file)
        return row_count

    def transform_dataframe(self, df: pd.DataFrame) -> pd.DataFrame:
        """Core transformation logic on pandas DataFrame."""
        raw_count = len(df)
        if raw_count == 0:
            return df

        # 1. Standardize column names
        df.columns = [
            re.sub(r"[^a-zA-Z0-9_]+", "_", str(col).strip().lower()).strip("_")
            for col in df.columns
        ]

        # 2. Trim string columns and convert string representations of null to None
        for col in df.columns:
            if df[col].dtype == object or pd.api.types.is_string_dtype(df[col]):
                df[col] = df[col].astype(str).str.strip()
                df[col] = df[col].replace({"nan": None, "None": None, "NULL": None, "null": None, "": None})

        # 3. Clean numeric fields (amount)
        if "amount" in df.columns:
            cleaned_amount = (
                df["amount"]
                .astype(str)
                .str.replace(r"[,$€£¥\s]", "", regex=True)
                .replace({"nan": None, "None": None, "": None})
            )
            df["amount"] = pd.to_numeric(cleaned_amount, errors="coerce")

        # 4. Clean and cast integer fields (order_id)
        if "order_id" in df.columns:
            cleaned_order_id = (
                df["order_id"]
                .astype(str)
                .str.replace(r"[^\d]", "", regex=True)
                .replace({"": None})
            )
            df["order_id"] = pd.to_numeric(cleaned_order_id, errors="coerce")

        # 5. Parse and standardize created_at timestamps (ISO 8601 UTC)
        if "created_at" in df.columns:
            df["created_at"] = pd.to_datetime(df["created_at"], utc=True, errors="coerce")

        # 6. Deduplicate by natural key (order_id) keeping first non-null
        if "order_id" in df.columns:
            df = df.dropna(subset=["order_id"])
            df["order_id"] = df["order_id"].astype("int64")
            df = df.drop_duplicates(subset=["order_id"], keep="first")

        # 7. Drop rows missing mandatory required fields (order_id or created_at)
        df_valid = df.dropna(subset=["order_id", "created_at"]) if "created_at" in df.columns else df.dropna(subset=["order_id"])

        # 8. Add audit timestamp
        df_valid = df_valid.copy()
        df_valid["ingested_at"] = pd.Timestamp.now(tz="UTC")

        # Select & order expected target columns if present
        target_columns = [
            "order_id",
            "customer_id",
            "customer_name",
            "customer_email",
            "product_category",
            "amount",
            "currency",
            "order_status",
            "created_at",
            "ingested_at",
        ]
        available_cols = [c for c in target_columns if c in df_valid.columns]
        df_valid = df_valid[available_cols]

        return df_valid

    def transform(self) -> int:
        """Schema-adaptive transformation with flexible parsing & circuit breaker."""
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file is empty. Nothing to transform.")
            return 0

        df = pd.read_parquet(self.staging_file)
        raw_count = len(df)
        if raw_count == 0:
            logger.warning("Staging DataFrame is empty. Nothing to transform.")
            return 0

        logger.info("Transforming %d raw records. Columns: %s", raw_count, list(df.columns))
        df_valid = self.transform_dataframe(df)
        valid_count = len(df_valid)
        quarantined = raw_count - valid_count

        if quarantined > 0:
            logger.warning("Quarantined / dropped %d invalid or duplicate records", quarantined)

        # Circuit breaker
        if raw_count > 0 and valid_count == 0:
            logger.error(
                "FATAL: 100%% of %d raw records were invalid or dropped. "
                "Failing pipeline via circuit breaker.", raw_count
            )
            sys.exit(1)

        df_valid.to_parquet(self.staging_file, index=False)
        logger.info("Transform complete: raw=%d, valid=%d, quarantined=%d", raw_count, valid_count, quarantined)
        return valid_count

    def load(self) -> bool:
        """Loads staged parquet records into Google BigQuery."""
        logger.info("Loading staged file %s into BigQuery...", self.staging_file)
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file %s is empty or missing. Skipping load.", self.staging_file)
            return True

        project_id = os.getenv("GCP_PROJECT_ID") or os.getenv("PROJECT_ID") or os.getenv("GOOGLE_CLOUD_PROJECT") or "upbeat-repeater-477110-q6"
        dataset_id = os.getenv("BIGQUERY_DATASET") or "sales_data"
        table_id = os.getenv("BIGQUERY_TABLE") or "cleaned_sales"
        write_mode = os.getenv("WRITE_MODE", "upsert").lower()

        from google.cloud import bigquery
        client = bigquery.Client(project=project_id)
        table_ref = f"{project_id}.{dataset_id}.{table_id}"

        df = pd.read_parquet(self.staging_file)

        # Configure Load Job
        write_disp = bigquery.WriteDisposition.WRITE_APPEND if write_mode == "append" else bigquery.WriteDisposition.WRITE_TRUNCATE
        job_config = bigquery.LoadJobConfig(write_disposition=write_disp)

        schema_file = os.path.join("schemas", "cleaned_sales_schema.json")
        if os.path.isfile(schema_file):
            job_config.schema = client.schema_from_json(schema_file)
            logger.info("Attached BigQuery schema from %s", schema_file)

        if write_mode == "append":
            job_config.schema_update_options = [
                bigquery.SchemaUpdateOption.ALLOW_FIELD_ADDITION,
                bigquery.SchemaUpdateOption.ALLOW_FIELD_RELAXATION,
            ]

        job = client.load_table_from_dataframe(df, table_ref, job_config=job_config)
        job.result()

        if job.errors:
            raise RuntimeError(f"FATAL: BigQuery load job failed: {job.errors}")

        logger.info("Successfully loaded %d records into BigQuery table: %s", len(df), table_ref)
        return True

    def run(self) -> int:
        """Executes full ETL pipeline."""
        logger.info("=== Starting sales_etl Pipeline Execution ===")
        extracted = self.extract()
        valid = self.transform()
        if extracted > 0 and valid == 0:
            logger.error("FATAL: Extracted %d records but 0 valid after transformation.", extracted)
            sys.exit(1)
        self.load()
        logger.info("=== sales_etl Pipeline Finished Successfully ===")
        return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Sales ETL Pipeline Runner")
    parser.add_argument("--date", help="Execution date (YYYY-MM-DD)", default=None)
    args = parser.parse_args()

    try:
        runner = PipelineRunner(execution_date=args.date)
        status = runner.run()
        if status != 0:
            sys.exit(1)
        sys.exit(0)
    except Exception as exc:
        logger.critical("Pipeline runner terminated with exception: %s", exc, exc_info=True)
        sys.exit(1)
