"""Standalone Connector Pipeline: sales_etl
Generated by SDLC Data Engineer Agent.
Architecture: GCS -> Local Staging -> BIGQUERY
Mock dummy data generation is completely disabled — real extraction & loading only.
"""
import os
import sys
import json
import logging
import argparse
from datetime import datetime

try:
    import pandas as pd
except ImportError:
    pd = None

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except ImportError:
    pa = None
    pq = None

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [%(name)s] %(message)s",
)
logger = logging.getLogger("sales_etl")


class PipelineRunner:
    def __init__(self, execution_date: str = None):
        self.execution_date = execution_date or datetime.utcnow().strftime("%Y-%m-%d")
        self.staging_dir = os.path.join("staging", "sales_etl", self.execution_date)
        os.makedirs(self.staging_dir, exist_ok=True)
        self.staging_file = os.path.join(self.staging_dir, "data.parquet")

    def extract(self) -> int:
        """Extracts data from real gcs into staging format.
        
        Zero-mock policy: if credentials or sources are unavailable, raises an error immediately.
        """
        logger.info("Starting real extraction from source: gcs...")
        if pd is None:
            raise RuntimeError("FATAL: pandas is required for pipeline execution.")
        from google.cloud import storage
        bucket_name = os.getenv("GCS_SOURCE_BUCKET") or "sdlc-workspec-store"
        prefix = os.getenv("GCS_SOURCE_PREFIX") or "etl/data/"
        if not bucket_name:
            raise EnvironmentError("FATAL: GCS source bucket not configured. Set GCS_SOURCE_BUCKET.")

        logger.info("Extracting real data from GCS bucket: gs://%s/%s", bucket_name, prefix)
        client = storage.Client()
        bucket = client.bucket(bucket_name)
        blobs = [b for b in bucket.list_blobs(prefix=prefix) if not b.name.endswith("/")]
        if not blobs:
            raise FileNotFoundError(f"FATAL: No data files found in gs://{bucket_name}/{prefix}. Mock fallback disabled.")

        dfs = []
        for blob in blobs:
            local_path = os.path.join(self.staging_dir, os.path.basename(blob.name))
            blob.download_to_filename(local_path)
            if local_path.endswith(".parquet"):
                dfs.append(pd.read_parquet(local_path))
            elif local_path.endswith(".csv"):
                dfs.append(pd.read_csv(local_path))
            elif local_path.endswith(".json") or local_path.endswith(".jsonl"):
                dfs.append(pd.read_json(local_path, lines=True))

        if not dfs:
            raise FileNotFoundError(f"FATAL: No parseable data files found in gs://{bucket_name}/{prefix}")

        df = pd.concat(dfs, ignore_index=True)
        row_count = len(df)
        df.to_parquet(self.staging_file, index=False)
        logger.info("Extracted %d real records from GCS to %s", row_count, self.staging_file)
        return row_count

    def transform(self) -> int:
        """Data cleansing, deduplication, and transformation.

        - Discovers columns dynamically from extracted DataFrame.
        - Trims whitespace, cleans strings, converts types.
        - Derives `order_date` from `created_at`.
        - Deduplicates on `order_id` retaining the latest timestamp.
        - Circuit breaker: if 100% of rows fail validation, exits with code 1.
        """
        if pd is None:
            raise RuntimeError("FATAL: pandas is required for transformation phase.")

        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file is empty. Nothing to transform.")
            return 0

        df = pd.read_parquet(self.staging_file)
        raw_count = len(df)
        if raw_count == 0:
            logger.warning("Staging DataFrame is empty. Nothing to transform.")
            return 0

        logger.info("Transforming %d raw records. Columns: %s", raw_count, list(df.columns))

        # Standardize column headers
        df.columns = [str(col).strip().lower() for col in df.columns]

        # String cleaning
        string_cols = ["customer_id", "customer_name", "customer_email", "product_category", "currency", "order_status"]
        for col in string_cols:
            if col in df.columns:
                df[col] = df[col].astype(str).str.strip()
                df[col] = df[col].replace({"nan": None, "None": None, "<NA>": None, "": None})

        # Primary Key cleaning
        if "order_id" in df.columns:
            df["order_id"] = df["order_id"].astype(str).str.strip()
            df["order_id"] = df["order_id"].replace({"nan": None, "None": None, "<NA>": None, "": None})

        # Amount numeric casting
        if "amount" in df.columns:
            df["amount"] = pd.to_numeric(df["amount"], errors="coerce")

        # Timestamp parsing
        if "created_at" in df.columns:
            df["created_at"] = pd.to_datetime(df["created_at"], utc=True, errors="coerce")
            df["order_date"] = df["created_at"].dt.date
        else:
            df["created_at"] = pd.Timestamp.now(tz="UTC")
            df["order_date"] = df["created_at"].dt.date

        # Metadata column
        df["_ingested_at"] = pd.Timestamp.now(tz="UTC")

        # Deduplication on order_id
        if "order_id" in df.columns and "created_at" in df.columns:
            df = df.sort_values(by="created_at", ascending=True)
            df = df.drop_duplicates(subset=["order_id"], keep="last")

        # Filter out records missing primary keys
        df_valid = df.dropna(subset=["order_id"]).copy()
        quarantined = raw_count - len(df_valid)
        if quarantined > 0:
            logger.warning("Quarantined %d invalid records", quarantined)

        # Circuit breaker check
        if raw_count > 0 and len(df_valid) == 0:
            logger.error(
                "FATAL: 100%% of %d raw records were quarantined due to missing primary key. "
                "Schema contract violation. Failing pipeline.", raw_count
            )
            sys.exit(1)

        # Ensure correct column ordering matching BigQuery schema
        expected_cols = [
            "order_id", "customer_id", "customer_name", "customer_email",
            "product_category", "amount", "currency", "order_status",
            "created_at", "order_date", "_ingested_at"
        ]
        for c in expected_cols:
            if c not in df_valid.columns:
                df_valid[c] = None

        df_valid = df_valid[expected_cols]

        # Save transformed records back to staging Parquet
        df_valid.to_parquet(self.staging_file, index=False)
        logger.info(
            "Transform complete: raw=%d, valid=%d, quarantined=%d",
            raw_count, len(df_valid), quarantined
        )
        return len(df_valid)

    def load(self) -> bool:
        """Loads staged records into real BigQuery destination.
        
        Zero-mock policy: if destination load fails, raises RuntimeError immediately.
        """
        logger.info("Loading staged file %s into BigQuery (analytics.harshada-test3)...", self.staging_file)
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file %s is empty or missing. Skipping load phase.", self.staging_file)
            return True

        project_id = (
            os.getenv("GCP_PROJECT_ID")
            or os.getenv("PROJECT_ID")
            or os.getenv("GOOGLE_CLOUD_PROJECT")
            or os.getenv("GCLOUD_PROJECT")
            or "upbeat-repeater-477110-q6"
        )
        dataset_id = os.getenv("BIGQUERY_DATASET") or "analytics"
        table_id = os.getenv("BIGQUERY_TABLE") or "harshada-test3"
        write_mode = "append"

        if not project_id:
            raise EnvironmentError("FATAL: GCP_PROJECT_ID or PROJECT_ID must be set for BigQuery loading.")

        from google.cloud import bigquery
        client = bigquery.Client(project=project_id)
        table_ref = f"{project_id}.{dataset_id}.{table_id}"

        if pd is None:
            raise RuntimeError("FATAL: pandas is required for loading phase.")

        df = pd.read_parquet(self.staging_file)

        job_config = bigquery.LoadJobConfig(
            write_disposition=bigquery.WriteDisposition.WRITE_APPEND if write_mode == "append" else bigquery.WriteDisposition.WRITE_TRUNCATE,
        )

        schema_file = os.path.join("schemas", "harshada-test3_schema.json")
        if os.path.isfile(schema_file):
            try:
                job_config.schema = client.schema_from_json(schema_file)
                logger.info("Attached explicit BigQuery schema from %s", schema_file)
            except Exception as schema_err:
                raise RuntimeError(f"FATAL: Could not parse schema file {schema_file}: {schema_err}") from schema_err

        if write_mode == "append":
            job_config.schema_update_options = [
                bigquery.SchemaUpdateOption.ALLOW_FIELD_ADDITION,
                bigquery.SchemaUpdateOption.ALLOW_FIELD_RELAXATION,
            ]

        job = client.load_table_from_dataframe(df, table_ref, job_config=job_config)
        job.result()  # Blocks until BigQuery load completes

        if job.errors:
            raise RuntimeError(f"FATAL: BigQuery load job failed: {job.errors}")

        logger.info("Successfully loaded %d records into BigQuery table: %s", len(df), table_ref)
        return True

    def run(self) -> int:
        """Executes the end-to-end connector pipeline with fail-fast semantics."""
        logger.info("=== Starting Connector Pipeline Execution ===")
        try:
            records = self.extract()
            if records == 0:
                logger.warning("Extraction completed with 0 records.")
            valid_count = self.transform()
            if records > 0 and valid_count == 0:
                logger.error(
                    "FATAL: Extracted %d records but 0 survived transformation. "
                    "Schema contract violation — failing pipeline.", records
                )
                return 1
            self.load()
            logger.info("=== Pipeline Execution Finished Successfully ===")
            return 0
        except SystemExit:
            raise  # Allow circuit breaker sys.exit(1) to propagate
        except Exception as exc:
            logger.critical("Pipeline execution FAILED: %s", exc, exc_info=True)
            raise RuntimeError(f"Pipeline execution FAILED: {exc}") from exc


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Connector Pipeline Runner")
    parser.add_argument("--date", help="Execution date (YYYY-MM-DD)", default=None)
    args = parser.parse_args()

    try:
        runner = PipelineRunner(execution_date=args.date)
        exit_code = runner.run()
        if exit_code != 0:
            sys.exit(1)
        sys.exit(0)
    except Exception as exc:
        logging.getLogger("sales_etl").critical("Pipeline failed with unhandled error: %s", exc, exc_info=True)
        raise exc
