"""Standalone Connector Pipeline: postgres_to_bigquery_scrum_352
Generated by SDLC Data Engineer Agent.
Architecture: POSTGRESQL -> Local Staging -> BIGQUERY
Mock dummy data generation is completely disabled — real extraction & loading only.
"""
import os
import sys
import json
import logging
import argparse
import uuid
from datetime import datetime, timezone

# Dependencies
try:
    import pandas as pd
except ImportError:
    pd = None

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except ImportError:
    pa = None
    pq = None

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [%(name)s] %(message)s",
)
logger = logging.getLogger("postgres_to_bigquery_scrum_352")


class PipelineRunner:
    def __init__(self, execution_date: str = None, batch_id: str = None):
        self.execution_date = execution_date or datetime.now(timezone.utc).strftime("%Y-%m-%d")
        self.batch_id = batch_id or str(uuid.uuid4())
        self.staging_dir = os.path.join("staging", "postgres_to_bigquery_scrum_352", self.execution_date)
        os.makedirs(self.staging_dir, exist_ok=True)
        self.staging_file = os.path.join(self.staging_dir, "data.parquet")

    def extract(self) -> int:
        """Extracts data from real postgresql into staging format.
        
        Zero-mock policy: if credentials or sources are unavailable, raises an error immediately.
        """
        logger.info("Starting real extraction from source: postgresql...")
        if pd is None:
            raise RuntimeError("FATAL: pandas is required for pipeline execution.")
        db_url = os.getenv("DATABASE_URL") or os.getenv("POSTGRES_URL")
        sql_engine = None
        sql_connector = None

        instance_connection_name = (
            os.getenv("INSTANCE_CONNECTION_NAME")
            or os.getenv("POSTGRES_INSTANCE_CONNECTION_NAME")
            or os.getenv("CLOUD_SQL_CONNECTION_NAME")
            or "upbeat-repeater-477110-q6:us-central1:sdlc-etl-demo-db"
        )
        host = os.getenv("POSTGRES_HOST") or os.getenv("DB_HOST", "")
        if not instance_connection_name and host and host.count(":") == 2:
            instance_connection_name = host
            host = ""

        port = os.getenv("POSTGRES_PORT") or os.getenv("DB_PORT", "5432")
        user = os.getenv("POSTGRES_USER") or os.getenv("DB_USER", "559906504681-compute@developer")
        password = os.getenv("POSTGRES_PASSWORD") or os.getenv("DB_PASSWORD", "")
        dbname = os.getenv("POSTGRES_DB") or os.getenv("DB_NAME", "postgres")

        # Approach 1: Official Google Cloud SQL Python Connector
        if instance_connection_name and user:
            try:
                import sqlalchemy
                from google.cloud.sql.connector import Connector, IPTypes
                logger.info("Connecting via Google Cloud SQL Connector for %s (IAM auth)", instance_connection_name)
                sql_connector = Connector()
                _is_iam = not bool(password)
                _ip_type = IPTypes.PRIVATE if (os.getenv("CLOUD_SQL_IP_TYPE", "PUBLIC").upper() == "PRIVATE") else IPTypes.PUBLIC
                def _getconn():
                    return sql_connector.connect(
                        instance_connection_name,
                        "pg8000",
                        user=user,
                        password=password if password else None,
                        db=dbname,
                        enable_iam_auth=_is_iam,
                        ip_type=_ip_type,
                    )
                sql_engine = sqlalchemy.create_engine("postgresql+pg8000://", creator=_getconn)
            except (ImportError, ModuleNotFoundError) as _import_err:
                logger.warning("Cloud SQL Python Connector module not available: %s", _import_err)
            except Exception as _conn_err:
                logger.error("Cloud SQL Python Connector initialization failed: %s", _conn_err)
                raise

        # Approach 2: Direct connection URL (host/IP fallback)
        if not sql_engine and not db_url:
            _is_iam = False
            if not password and user:
                try:
                    import google.auth
                    from google.auth.transport.requests import Request
                    _iam_creds, _ = google.auth.default(scopes=["https://www.googleapis.com/auth/sqlservice.admin"])
                    _iam_creds.refresh(Request())
                    if _iam_creds.token:
                        password = _iam_creds.token
                        _is_iam = True
                        logger.info("Generated ephemeral Google IAM OAuth2 token for Cloud SQL authentication")
                except (ImportError, AttributeError, ValueError) as _iam_err:
                    logger.warning("IAM token generation skipped: %s", _iam_err)

            if user and host and dbname:
                import urllib.parse
                _enc_pw = urllib.parse.quote_plus(password) if password else ""
                _ssl = "?sslmode=require" if _is_iam else ""
                db_url = f"postgresql://{user}:{_enc_pw}@{host}:{port}/{dbname}{_ssl}"

        con_target = sql_engine if sql_engine is not None else db_url
        if not con_target:
            raise EnvironmentError(
                "FATAL: Database connection parameters missing. Provide INSTANCE_CONNECTION_NAME, "
                "DATABASE_URL, or POSTGRES_* environment variables. Mock dummy data is disabled."
            )

        source_table = os.getenv("SOURCE_TABLE", "test_data")
        query = f"SELECT * FROM {source_table}"
        logger.info("Executing extraction query against PostgreSQL: %s", query)
        try:
            df = pd.read_sql(query, con=con_target)
        finally:
            if sql_engine is not None:
                sql_engine.dispose()
            if sql_connector is not None:
                sql_connector.close()

        row_count = len(df)
        df.to_parquet(self.staging_file, index=False)
        logger.info("Extracted %d real records to %s", row_count, self.staging_file)
        return row_count

    def transform(self) -> int:
        """Schema-adaptive transformation with cleaning and audit metadata."""
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file is empty. Nothing to transform.")
            return 0

        df = pd.read_parquet(self.staging_file)
        raw_count = len(df)
        if raw_count == 0:
            logger.warning("Staging DataFrame is empty. Nothing to transform.")
            return 0

        logger.info("Transforming %d raw records. Columns: %s", raw_count, list(df.columns))

        # ── 1. Column name standardization ──
        df.columns = [str(col).strip().lower() for col in df.columns]

        # ── 2. Whitespace trimming and null sanitization ──
        null_markers = {"", "null", "none", "n/a", "na", "\\n", "nan"}
        for col in df.columns:
            if df[col].dtype == object or pd.api.types.is_string_dtype(df[col]):
                df[col] = df[col].apply(
                    lambda v: None
                    if v is None or (isinstance(v, str) and (v.strip().lower() in null_markers or not v.strip()))
                    else (v.strip() if isinstance(v, str) else v)
                )

        # ── 3. Specification-Driven Column Transformations ──────────
        if "id" in df.columns:
            df["id"] = pd.to_numeric(df["id"], errors="coerce").astype("Int64")
            logger.info("Applied transformation to id -> INT64")
        if "data_val" in df.columns:
            df["data_val"] = df["data_val"].astype(str).replace({"<NA>": None, "nan": None, "None": None})
            logger.info("Applied transformation to data_val -> STRING")
        if "created_at" in df.columns:
            df["created_at"] = pd.to_datetime(df["created_at"], utc=True)
            logger.info("Applied transformation to created_at -> TIMESTAMP")

        # ── 4. Deduplication ──
        if "id" in df.columns:
            df = df.drop_duplicates(subset=["id"], keep="last")
        else:
            df = df.drop_duplicates(keep="last")

        # ── 5. Basic validity filter (non-empty rows only) ─────────
        df_valid = df.dropna(how="all")
        quarantined = raw_count - len(df_valid)
        if quarantined > 0:
            logger.warning("Quarantined %d invalid/empty records", quarantined)

        # ── 6. Circuit breaker ─────────────────────────────────────
        anomaly_threshold = float(os.getenv("CIRCUIT_BREAKER_THRESHOLD", "0.05"))
        if raw_count > 0 and (quarantined / float(raw_count)) > anomaly_threshold:
            logger.error(
                "FATAL: %d of %d raw records (%.2f%%) were quarantined, exceeding threshold %.2f%%. "
                "Failing the pipeline.",
                quarantined,
                raw_count,
                (quarantined / float(raw_count)) * 100,
                anomaly_threshold * 100,
            )
            sys.exit(1)

        # ── 7. Add ingestion audit columns ───────────────────────
        df_valid = df_valid.copy()
        df_valid["_etl_loaded_at"] = datetime.now(timezone.utc)
        df_valid["_etl_batch_id"] = self.batch_id

        # Overwrite staging file with cleaned data
        df_valid.to_parquet(self.staging_file, index=False)
        logger.info(
            "Transform complete: raw=%d, valid=%d, quarantined=%d",
            raw_count, len(df_valid), quarantined,
        )
        return len(df_valid)

    def load(self) -> bool:
        """Loads staged records into real bigquery destination."""
        logger.info("Loading staged file %s into BigQuery...", self.staging_file)
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file %s is empty or missing. Skipping load phase.", self.staging_file)
            return True

        project_id = os.getenv("GCP_PROJECT_ID") or os.getenv("PROJECT_ID") or "upbeat-repeater-477110-q6"
        dataset_id = os.getenv("BIGQUERY_DATASET") or "analytics"
        table_id = os.getenv("BIGQUERY_TABLE") or "postgres_test1"
        write_mode = os.getenv("WRITE_MODE", "truncate").lower()

        from google.cloud import bigquery
        client = bigquery.Client(project=project_id)
        table_ref = f"{project_id}.{dataset_id}.{table_id}"

        df = pd.read_parquet(self.staging_file)

        disposition = (
            bigquery.WriteDisposition.WRITE_APPEND
            if write_mode == "append"
            else bigquery.WriteDisposition.WRITE_TRUNCATE
        )
        job_config = bigquery.LoadJobConfig(
            write_disposition=disposition,
        )

        schema_file = os.path.join("schemas", "postgres_test1_schema.json")
        if os.path.isfile(schema_file):
            try:
                job_config.schema = client.schema_from_json(schema_file)
                logger.info("Attached explicit BigQuery schema from %s", schema_file)
            except (json.JSONDecodeError, OSError, ValueError) as schema_err:
                logger.warning("Could not attach schema from %s: %s", schema_file, schema_err)

        job = client.load_table_from_dataframe(df, table_ref, job_config=job_config)
        job.result()  # Blocks until BigQuery load completes

        if job.errors:
            raise RuntimeError(f"FATAL: BigQuery load job failed: {job.errors}")

        logger.info("Successfully loaded %d records into BigQuery table: %s", len(df), table_ref)
        return True

    def run(self) -> int:
        """Executes the end-to-end connector pipeline with fail-fast semantics."""
        logger.info("=== Starting Connector Pipeline Execution ===")
        try:
            records = self.extract()
            if records == 0:
                logger.warning("Extraction completed with 0 records.")
            valid_count = self.transform()
            if records > 0 and valid_count == 0:
                logger.error(
                    "FATAL: Extracted %d records but 0 survived transformation. "
                    "Schema contract violation — failing pipeline.", records
                )
                sys.exit(1)
            self.load()
            logger.info("=== Pipeline Execution Finished Successfully ===")
            return 0
        except SystemExit:
            raise
        except Exception as exc:
            logger.critical("Pipeline execution FAILED: %s", exc, exc_info=True)
            sys.exit(1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Connector Pipeline Runner")
    parser.add_argument("--date", help="Execution date (YYYY-MM-DD)", default=None)
    parser.add_argument("--batch-id", help="Batch UUID", default=None)
    args = parser.parse_args()

    runner = PipelineRunner(execution_date=args.date, batch_id=args.batch_id)
    exit_code = runner.run()
    sys.exit(exit_code)
