"""Standalone Connector Pipeline: postgres_to_bigquery_kttest
Generated by SDLC Data Engineer Agent.
Architecture: POSTGRESQL -> Local Staging -> BIGQUERY
Mock dummy data generation is completely disabled — real extraction & loading only.
"""
import os
import sys
import json
import logging
import argparse
from datetime import datetime

import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
from google.cloud import bigquery
from google.cloud.exceptions import NotFound

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [%(name)s] %(message)s",
)
logger = logging.getLogger("postgres_to_bigquery_kttest")


class PipelineRunner:
    def __init__(self, execution_date: str = None):
        self.execution_date = execution_date or datetime.utcnow().strftime("%Y-%m-%d")
        self.staging_dir = os.path.join("staging", "postgres_to_bigquery_kttest", self.execution_date)
        os.makedirs(self.staging_dir, exist_ok=True)
        self.staging_file = os.path.join(self.staging_dir, "data.parquet")

    def extract(self) -> int:
        """Extracts data from real postgresql into staging format.
        
        Zero-mock policy: if credentials or sources are unavailable, raises an error immediately.
        """
        logger.info("Starting real extraction from source: postgresql...")
        db_url = os.getenv("DATABASE_URL") or os.getenv("POSTGRES_URL")
        sql_engine = None
        sql_connector = None

        instance_connection_name = (
            os.getenv("INSTANCE_CONNECTION_NAME")
            or os.getenv("POSTGRES_INSTANCE_CONNECTION_NAME")
            or os.getenv("CLOUD_SQL_CONNECTION_NAME")
            or ""
        )
        host = os.getenv("POSTGRES_HOST") or os.getenv("DB_HOST", "")
        if not instance_connection_name and host and host.count(":") == 2:
            instance_connection_name = host
            host = ""

        port = os.getenv("POSTGRES_PORT") or os.getenv("DB_PORT", "5432")
        user = os.getenv("POSTGRES_USER") or os.getenv("DB_USER", "")
        dbname = os.getenv("POSTGRES_DB") or os.getenv("DB_NAME", "")
        # NOTE: POSTGRES_PASSWORD is intentionally NOT read here.
        # All Cloud SQL connections use IAM database authentication.

        # Cloud SQL Python Connector with mandatory IAM Authentication
        if instance_connection_name and user:
            try:
                import sqlalchemy
                from google.cloud.sql.connector import Connector, IPTypes
                logger.info(
                    "Connecting via Cloud SQL Python Connector for %s (IAM auth, user=%s)",
                    instance_connection_name, user
                )
                sql_connector = Connector()
                _ip_type = IPTypes.PRIVATE if (os.getenv("CLOUD_SQL_IP_TYPE", "PRIVATE").upper() == "PRIVATE") else IPTypes.PUBLIC

                def _getconn():
                    return sql_connector.connect(
                        instance_connection_name,
                        "pg8000",
                        user=user,
                        db=dbname,
                        enable_iam_auth=True,
                        ip_type=_ip_type,
                    )

                sql_engine = sqlalchemy.create_engine("postgresql+pg8000://", creator=_getconn)
            except Exception as _conn_err:
                logger.error(
                    "FATAL: Cloud SQL Python Connector initialization failed: %s. "
                    "Ensure cloud-sql-python-connector is in requirements.txt and "
                    "INSTANCE_CONNECTION_NAME, POSTGRES_USER, POSTGRES_DB are set correctly.",
                    _conn_err
                )
                raise RuntimeError(f"Cloud SQL connector failed: {_conn_err}") from _conn_err

        con_target = sql_engine if sql_engine is not None else db_url
        if not con_target:
            raise EnvironmentError(
                "FATAL: Database connection parameters missing. "
                "Provide INSTANCE_CONNECTION_NAME + POSTGRES_USER + POSTGRES_DB for Cloud SQL IAM auth, "
                "or DATABASE_URL for direct connection. Mock dummy data is disabled."
            )

        source_tbl = os.getenv("SOURCE_TABLE", "kttest_data")
        query = f"SELECT * FROM {source_tbl}"
        logger.info("Executing extraction query against PostgreSQL: %s", query)
        try:
            df = pd.read_sql(query, con=con_target)
        except Exception as q_err:
            logger.error("Failed to execute extraction query '%s': %s", query, q_err)
            raise RuntimeError(f"Extraction failed: {q_err}") from q_err
        finally:
            if sql_engine is not None:
                sql_engine.dispose()
            if sql_connector is not None:
                sql_connector.close()

        row_count = len(df)
        df.to_parquet(self.staging_file, index=False)
        logger.info("Extracted %d real records to %s", row_count, self.staging_file)
        return row_count

    def transform(self) -> int:
        """Schema-adaptive transformation with flexible parsing.

        - Discovers columns dynamically from the extracted DataFrame.
        - Normalizes column names and trims whitespace.
        - Normalizes nulls and removes duplicate rows.
        - Parses date/timestamp columns.
        - Circuit breaker: if 100% of rows fail validation, raises RuntimeError.
        """
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file is empty. Nothing to transform.")
            return 0

        df = pd.read_parquet(self.staging_file)
        raw_count = len(df)
        if raw_count == 0:
            logger.warning("Staging DataFrame is empty. Nothing to transform.")
            return 0

        logger.info("Transforming %d raw records. Columns: %s", raw_count, list(df.columns))

        import re
        df.columns = [
            re.sub(r"[^a-zA-Z0-9_]+", "_", str(col).strip().lower()).strip("_")
            for col in df.columns
        ]
        logger.info("Standardized columns: %s", list(df.columns))

        # Vectorized string trimming and null normalization
        for col in df.select_dtypes(include=["object", "string"]).columns:
            df[col] = df[col].astype(str).str.strip().replace({"nan": None, "None": None, "null": None, "NULL": None, "": None})

        # Deduplication
        initial_count = len(df)
        df = df.drop_duplicates()
        dupes_dropped = initial_count - len(df)
        if dupes_dropped > 0:
            logger.info("Removed %d duplicate records", dupes_dropped)

        # Drop rows where all columns are null
        df_valid = df.dropna(how="all")
        quarantined = raw_count - len(df_valid)
        if quarantined > 0:
            logger.warning("Quarantined %d fully-null records", quarantined)

        # Circuit breaker
        if raw_count > 0 and len(df_valid) == 0:
            logger.error(
                "FATAL: 100%% of %d raw records were quarantined. "
                "Schema contract violation.", raw_count
            )
            raise RuntimeError(f"All {raw_count} records were quarantined.")

        # Ingestion audit timestamp
        df_valid = df_valid.copy()
        df_valid["ingested_at"] = datetime.utcnow().isoformat()

        # Overwrite staging file with cleaned data
        df_valid.to_parquet(self.staging_file, index=False)
        logger.info(
            "Transform complete: raw=%d, valid=%d, quarantined=%d",
            raw_count, len(df_valid), quarantined,
        )
        return len(df_valid)

    def load(self) -> bool:
        """Loads staged records into real bigquery destination.
        
        Zero-mock policy: if destination load fails, raises RuntimeError immediately.
        """
        logger.info("Loading staged file %s into BigQuery...", self.staging_file)
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file %s is empty or missing. Skipping load phase.", self.staging_file)
            return True

        project_id = os.getenv("GCP_PROJECT_ID") or os.getenv("PROJECT_ID") or os.getenv("GOOGLE_CLOUD_PROJECT") or "upbeat-repeater-477110-q6"
        dataset_id = os.getenv("BIGQUERY_DATASET") or "analytics"
        table_id = os.getenv("BIGQUERY_TABLE") or "postgres_test2"
        write_mode = "append"

        try:
            client = bigquery.Client(project=project_id)
        except Exception as client_init_err:
            logger.error("Failed to initialize BigQuery client for project %s: %s", project_id, client_init_err)
            raise EnvironmentError(
                f"FATAL: Unable to initialize BigQuery client (project_id='{project_id}'): {client_init_err}"
            ) from client_init_err

        table_ref = f"{project_id}.{dataset_id}.{table_id}"

        # Pre-create target dataset if it does not exist
        try:
            dataset_ref = client.dataset(dataset_id, project=project_id)
            try:
                client.get_dataset(dataset_ref)
            except NotFound:
                ds = bigquery.Dataset(dataset_ref)
                ds.location = os.getenv("BQ_LOCATION", "us-central1")
                client.create_dataset(ds, exists_ok=True)
                logger.info("Created target BigQuery dataset '%s'.", dataset_ref)
        except NotFound:
            ds = bigquery.Dataset(dataset_ref)
            ds.location = os.getenv("BQ_LOCATION", "us-central1")
            client.create_dataset(ds, exists_ok=True)
            logger.info("Created target BigQuery dataset '%s'.", dataset_ref)
        except Exception as ds_err:
            logger.error("Dataset check/creation error for '%s': %s", dataset_id, ds_err)
            raise RuntimeError(f"BigQuery dataset verification failed: {ds_err}") from ds_err

        df = pd.read_parquet(self.staging_file)

        job_config = bigquery.LoadJobConfig(
            write_disposition=bigquery.WriteDisposition.WRITE_APPEND if write_mode == "append" else bigquery.WriteDisposition.WRITE_TRUNCATE,
            create_disposition=bigquery.CreateDisposition.CREATE_IF_NEEDED,
        )

        schema_file = None
        for cand in [
            os.path.join("schemas", f"{table_id}_schema.json"),
            os.path.join("schemas", "postgres_test2_schema.json"),
            os.path.join("schemas", "target_table_schema.json"),
        ]:
            if os.path.isfile(cand):
                schema_file = cand
                break

        if schema_file:
            try:
                raw_schema = client.schema_from_json(schema_file)
                reconciled_schema = []
                for field in raw_schema:
                    if field.name not in df.columns:
                        df[field.name] = None
                        reconciled_schema.append(
                            bigquery.SchemaField(
                                name=field.name,
                                field_type=field.field_type,
                                mode="NULLABLE",
                                description=field.description,
                            )
                        )
                    else:
                        reconciled_schema.append(field)

                schema_col_names = {sf.name for sf in raw_schema}
                for col in df.columns:
                    if col not in schema_col_names:
                        reconciled_schema.append(
                            bigquery.SchemaField(
                                name=col,
                                field_type="STRING",
                                mode="NULLABLE",
                                description=f"Dynamically discovered column '{col}'",
                            )
                        )

                # Type-safe coercion
                for field in reconciled_schema:
                    col = field.name
                    f_type = field.field_type.upper()
                    if col in df.columns:
                        if f_type in ("INTEGER", "INT64"):
                            df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")
                        elif f_type in ("FLOAT", "FLOAT64", "NUMERIC", "BIGNUMERIC"):
                            df[col] = pd.to_numeric(df[col], errors="coerce")
                        elif f_type in ("TIMESTAMP", "DATETIME"):
                            df[col] = pd.to_datetime(df[col], errors="coerce", utc=True)
                        elif f_type in ("BOOLEAN", "BOOL"):
                            df[col] = df[col].map(
                                lambda v: True if str(v).strip().lower() in ("true", "1", "t", "yes")
                                else (False if str(v).strip().lower() in ("false", "0", "f", "no") else None)
                                if pd.notna(v) else None
                            ).astype("boolean")
                        elif f_type == "STRING":
                            df[col] = df[col].apply(lambda v: str(v) if pd.notna(v) else None)

                job_config.schema = reconciled_schema
                logger.info("Attached and reconciled explicit BigQuery schema from %s (%d fields)", schema_file, len(reconciled_schema))
            except Exception as schema_err:
                logger.error("Schema attachment error from %s: %s", schema_file, schema_err)
                raise RuntimeError(f"Failed to process schema from {schema_file}: {schema_err}") from schema_err
        else:
            job_config.autodetect = True

        if write_mode == "append":
            job_config.schema_update_options = [
                bigquery.SchemaUpdateOption.ALLOW_FIELD_ADDITION,
                bigquery.SchemaUpdateOption.ALLOW_FIELD_RELAXATION,
            ]

        try:
            job = client.load_table_from_dataframe(df, table_ref, job_config=job_config)
            job.result()
        except Exception as load_err:
            logger.error("Primary load_table_from_dataframe failed: %s", load_err)
            raise RuntimeError(f"BigQuery load failed for table {table_ref}: {load_err}") from load_err

        logger.info("Successfully loaded %d records into BigQuery table: %s", len(df), table_ref)
        return True

    def run(self) -> int:
        """Executes the end-to-end connector pipeline with fail-fast semantics."""
        logger.info("=== Starting Connector Pipeline Execution ===")
        try:
            records = self.extract()
            if records == 0:
                logger.warning("Extraction completed with 0 records.")
                return 0
            valid_count = self.transform()
            if records > 0 and valid_count == 0:
                logger.error(
                    "FATAL: Extracted %d records but 0 survived transformation. "
                    "Schema contract violation — failing pipeline.", records
                )
                raise RuntimeError("All extracted records were invalid after transformation.")
            self.load()
            logger.info("=== Pipeline Execution Finished Successfully ===")
            return 0
        except Exception as exc:
            logger.critical("Pipeline execution FAILED: %s", exc, exc_info=True)
            raise


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Connector Pipeline Runner")
    parser.add_argument("--date", help="Execution date (YYYY-MM-DD)", default=None)
    args = parser.parse_args()

    try:
        runner = PipelineRunner(execution_date=args.date)
        exit_code = runner.run()
        if exit_code != 0:
            sys.exit(1)
        sys.exit(0)
    except Exception as exc:
        logging.getLogger("postgres_to_bigquery_kttest").critical("Pipeline failed with unhandled error: %s", exc, exc_info=True)
        sys.exit(1)
