"""Standalone Connector Pipeline: postgres_to_bigquery_scrum_386
Generated by SDLC Data Engineer Agent.
Architecture: POSTGRESQL -> Local Staging -> BIGQUERY
Mock dummy data generation is completely disabled — real extraction & loading only.
"""
import os
import sys
import json
import re
import logging
import argparse
from datetime import datetime, timezone
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import sqlalchemy
from google.cloud import bigquery
from google.cloud.sql.connector import Connector, IPTypes

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [%(name)s] %(message)s",
)
logger = logging.getLogger("postgres_to_bigquery_scrum_386")


class PipelineRunner:
    def __init__(self, execution_date: str = None):
        self.execution_date = execution_date or datetime.now(timezone.utc).strftime("%Y-%m-%d")
        self.staging_dir = os.path.join("staging", "postgres_to_bigquery_scrum_386", self.execution_date)
        os.makedirs(self.staging_dir, exist_ok=True)
        self.staging_file = os.path.join(self.staging_dir, "data.parquet")

    def extract(self) -> int:
        """Extracts data from real postgresql into staging format.
        
        Zero-mock policy: if credentials or sources are unavailable, raises an error immediately.
        """
        logger.info("Starting real extraction from source: postgresql...")
        db_url = os.getenv("DATABASE_URL") or os.getenv("POSTGRES_URL")
        sql_engine = None
        sql_connector = None

        instance_connection_name = (
            os.getenv("INSTANCE_CONNECTION_NAME")
            or os.getenv("POSTGRES_INSTANCE_CONNECTION_NAME")
            or os.getenv("CLOUD_SQL_CONNECTION_NAME")
            or ""
        )
        host = os.getenv("POSTGRES_HOST") or os.getenv("DB_HOST", "")
        if not instance_connection_name and host and host.count(":") == 2:
            instance_connection_name = host
            host = ""

        user = os.getenv("POSTGRES_USER") or os.getenv("DB_USER", "")
        dbname = os.getenv("POSTGRES_DB") or os.getenv("DB_NAME", "")
        # NOTE: POSTGRES_PASSWORD is intentionally NOT read here.
        # All Cloud SQL connections use IAM database authentication.

        if instance_connection_name and user:
            try:
                logger.info(
                    "Connecting via Cloud SQL Python Connector for %s (IAM auth, user=%s)",
                    instance_connection_name, user
                )
                sql_connector = Connector()
                _ip_type = IPTypes.PRIVATE if (os.getenv("CLOUD_SQL_IP_TYPE", "PRIVATE").upper() == "PRIVATE") else IPTypes.PUBLIC
                def _getconn():
                    return sql_connector.connect(
                        instance_connection_name,
                        "pg8000",
                        user=user,
                        db=dbname,
                        enable_iam_auth=True,
                        ip_type=_ip_type,
                    )
                sql_engine = sqlalchemy.create_engine("postgresql+pg8000://", creator=_getconn)
            except Exception as _conn_err:
                logger.error("FATAL: Cloud SQL Python Connector initialization failed: %s", _conn_err)
                raise RuntimeError(f"Cloud SQL connector failed: {_conn_err}") from _conn_err

        con_target = sql_engine if sql_engine is not None else db_url
        if not con_target:
            raise EnvironmentError(
                "FATAL: Database connection parameters missing. "
                "Provide INSTANCE_CONNECTION_NAME + POSTGRES_USER + POSTGRES_DB for Cloud SQL IAM auth, "
                "or DATABASE_URL for direct connection. Mock dummy data is disabled."
            )

        source_table = os.getenv("POSTGRES_TABLE") or os.getenv("SOURCE_TABLE") or "test_data"
        query = f"SELECT * FROM {source_table}"
        logger.info("Executing extraction query against PostgreSQL: %s", query)
        try:
            df = pd.read_sql(query, con=con_target)
        except Exception as _query_err:
            logger.error("Extraction query failed: %s", _query_err)
            raise RuntimeError(f"Extraction failed: {_query_err}") from _query_err
        finally:
            if sql_engine is not None:
                sql_engine.dispose()
            if sql_connector is not None:
                sql_connector.close()

        row_count = len(df)
        df.to_parquet(self.staging_file, index=False)
        logger.info("Extracted %d real records to %s", row_count, self.staging_file)
        return row_count

    def transform(self) -> int:
        """Schema-adaptive transformation with flexible parsing."""
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file is empty. Nothing to transform.")
            return 0

        df = pd.read_parquet(self.staging_file)
        raw_count = len(df)
        if raw_count == 0:
            logger.warning("Staging DataFrame is empty. Nothing to transform.")
            return 0

        logger.info("Transforming %d raw records. Columns: %s", raw_count, list(df.columns))

        df.columns = [
            re.sub(r"[^a-zA-Z0-9_]+", "_", str(col).strip().lower()).strip("_")
            for col in df.columns
        ]

        # Standardize string columns and null representations
        null_literals = {"", "null", "none", "n/a", "nan", "nil", "undefined"}
        for col in df.select_dtypes(include=["object", "string"]).columns:
            df[col] = df[col].apply(lambda val: str(val).strip() if pd.notna(val) else None)
            df[col] = df[col].apply(lambda val: None if (val is None or str(val).lower() in null_literals) else val)

        # Drop rows where all columns are null
        df_valid = df.dropna(how="all").drop_duplicates().copy()
        quarantined = raw_count - len(df_valid)
        if quarantined > 0:
            logger.warning("Quarantined / dropped %d invalid/duplicate records", quarantined)

        # Circuit breaker
        if raw_count > 0 and len(df_valid) == 0:
            logger.error("FATAL: 100%% of %d raw records were quarantined.", raw_count)
            sys.exit(1)

        # Add ingestion audit timestamp and source metadata
        df_valid["_etl_loaded_at"] = datetime.now(timezone.utc)
        df_valid["_etl_source_table"] = f"postgres.{os.getenv('POSTGRES_TABLE', 'test_data')}"

        df_valid.to_parquet(self.staging_file, index=False)
        logger.info("Transform complete: raw=%d, valid=%d, quarantined=%d", raw_count, len(df_valid), quarantined)
        return len(df_valid)

    def load(self) -> bool:
        """Loads staged records into real BigQuery destination."""
        logger.info("Loading staged file %s into BigQuery...", self.staging_file)
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file %s is empty or missing. Skipping load phase.", self.staging_file)
            return True

        project_id = os.getenv("GCP_PROJECT_ID") or "upbeat-repeater-477110-q6"
        dataset_id = os.getenv("BIGQUERY_DATASET") or "analytics"
        table_id = os.getenv("BIGQUERY_TABLE") or "postgres_test4"
        write_mode = os.getenv("WRITE_DISPOSITION", "WRITE_APPEND").upper()

        try:
            client = bigquery.Client(project=project_id)
        except Exception as client_init_err:
            raise EnvironmentError(
                f"FATAL: Unable to initialize BigQuery client (project_id='{project_id}'): {client_init_err}"
            ) from client_init_err

        table_ref = f"{project_id}.{dataset_id}.{table_id}"

        # Ensure dataset
        dataset_ref = client.dataset(dataset_id, project=project_id)
        ds = bigquery.Dataset(dataset_ref)
        ds.location = os.getenv("BQ_LOCATION", "us-central1")
        client.create_dataset(ds, exists_ok=True)

        df = pd.read_parquet(self.staging_file)
        job_config = bigquery.LoadJobConfig(
            write_disposition=bigquery.WriteDisposition.WRITE_APPEND if write_mode == "WRITE_APPEND" else bigquery.WriteDisposition.WRITE_TRUNCATE,
            create_disposition=bigquery.CreateDisposition.CREATE_IF_NEEDED,
        )

        schema_file = os.path.join("schemas", f"{table_id}_schema.json")
        if os.path.isfile(schema_file):
            raw_schema = client.schema_from_json(schema_file)
            reconciled_schema = []
            schema_col_names = set()
            for field in raw_schema:
                schema_col_names.add(field.name)
                if field.name not in df.columns:
                    df[field.name] = None
                    reconciled_schema.append(
                        bigquery.SchemaField(
                            name=field.name,
                            field_type=field.field_type,
                            mode="NULLABLE",
                            description=field.description,
                        )
                    )
                else:
                    reconciled_schema.append(field)

            for col in df.columns:
                if col not in schema_col_names:
                    reconciled_schema.append(
                        bigquery.SchemaField(
                            name=col,
                            field_type="STRING",
                            mode="NULLABLE",
                            description=f"Dynamically discovered column '{col}'",
                        )
                    )

            # Type safe coercion
            for field in reconciled_schema:
                col = field.name
                f_type = field.field_type.upper()
                if col in df.columns:
                    if f_type in ("INTEGER", "INT64"):
                        df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")
                    elif f_type in ("FLOAT", "FLOAT64", "NUMERIC", "BIGNUMERIC"):
                        df[col] = pd.to_numeric(df[col], errors="coerce")
                    elif f_type in ("TIMESTAMP", "DATETIME"):
                        df[col] = pd.to_datetime(df[col], errors="coerce", utc=True)
                    elif f_type in ("BOOLEAN", "BOOL"):
                        df[col] = df[col].map(
                            lambda v: True if str(v).strip().lower() in ("true", "1", "t", "yes")
                            else (False if str(v).strip().lower() in ("false", "0", "f", "no") else None)
                            if pd.notna(v) else None
                        ).astype("boolean")
                    elif f_type == "STRING":
                        df[col] = df[col].apply(lambda v: str(v) if pd.notna(v) else None)

            job_config.schema = reconciled_schema

        if write_mode == "WRITE_APPEND":
            job_config.schema_update_options = [
                bigquery.SchemaUpdateOption.ALLOW_FIELD_ADDITION,
                bigquery.SchemaUpdateOption.ALLOW_FIELD_RELAXATION,
            ]

        try:
            job = client.load_table_from_dataframe(df, table_ref, job_config=job_config)
            job.result()
        except Exception as load_err:
            logger.error("BigQuery load_table_from_dataframe failed: %s", load_err)
            raise RuntimeError(f"BigQuery load failed: {load_err}") from load_err

        logger.info("Successfully loaded %d records into BigQuery table: %s", len(df), table_ref)
        return True

    def run(self) -> int:
        """Executes the end-to-end connector pipeline with fail-fast semantics."""
        logger.info("=== Starting Connector Pipeline Execution ===")
        try:
            records = self.extract()
            valid_count = self.transform()
            if records > 0 and valid_count == 0:
                logger.error("Extracted %d records but 0 survived transformation.", records)
                sys.exit(1)
            self.load()
            logger.info("=== Pipeline Execution Finished Successfully ===")
            return 0
        except SystemExit:
            raise
        except Exception as exc:
            logger.critical("Pipeline execution FAILED: %s", exc, exc_info=True)
            sys.exit(1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Connector Pipeline Runner")
    parser.add_argument("--date", help="Execution date (YYYY-MM-DD)", default=None)
    args = parser.parse_args()

    runner = PipelineRunner(execution_date=args.date)
    exit_code = runner.run()
    sys.exit(exit_code)
