"""Standalone Connector Pipeline: test03_pipeline
Generated by SDLC Data Engineer Agent.
Architecture: GCS -> Local Staging -> BigQuery (upbeat-repeater-477110-q6.analytics.test03)
Extracts CSV from GCS, cleanses, sorts by rank ascending, and loads into BigQuery.
"""
import os
import sys
import json
import logging
import argparse
import re
from datetime import datetime, timezone

try:
    import pandas as pd
except ImportError:
    pd = None

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except ImportError:
    pa = None
    pq = None

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [%(name)s] %(message)s",
)
logger = logging.getLogger("test03_pipeline")


class PipelineRunner:
    def __init__(self, execution_date: str = None):
        self.execution_date = execution_date or datetime.now(timezone.utc).strftime("%Y-%m-%d")
        self.staging_dir = os.path.join("staging", "test03_pipeline", self.execution_date)
        os.makedirs(self.staging_dir, exist_ok=True)
        self.staging_file = os.path.join(self.staging_dir, "data.parquet")

    def extract(self) -> int:
        """Extracts data from real GCS into staging format."""
        logger.info("Starting real extraction from source: GCS...")
        if pd is None:
            raise RuntimeError("FATAL: pandas is required for pipeline execution.")
        from google.cloud import storage
        bucket_name = os.getenv("GCS_SOURCE_BUCKET") or "sdlc-workspec-store"
        prefix = os.getenv("GCS_SOURCE_PREFIX") or "etl/data/my_file (1).csv"
        if not bucket_name:
            raise EnvironmentError("FATAL: GCS source bucket not configured. Set GCS_SOURCE_BUCKET.")

        logger.info("Extracting real data from GCS bucket: gs://%s/%s", bucket_name, prefix)
        client = storage.Client()
        bucket = client.bucket(bucket_name)

        blob = bucket.blob(prefix)
        dfs = []
        if blob.exists():
            local_path = os.path.join(self.staging_dir, os.path.basename(prefix))
            blob.download_to_filename(local_path)
            if local_path.endswith(".parquet"):
                dfs.append(pd.read_parquet(local_path))
            elif local_path.endswith(".csv"):
                dfs.append(pd.read_csv(local_path))
            elif local_path.endswith(".json") or local_path.endswith(".jsonl"):
                dfs.append(pd.read_json(local_path, lines=True))
        else:
            blobs = [b for b in bucket.list_blobs(prefix=os.path.dirname(prefix)) if not b.name.endswith("/")]
            for b in blobs:
                if os.path.basename(b.name) == os.path.basename(prefix):
                    local_path = os.path.join(self.staging_dir, os.path.basename(b.name))
                    b.download_to_filename(local_path)
                    if local_path.endswith(".parquet"):
                        dfs.append(pd.read_parquet(local_path))
                    elif local_path.endswith(".csv"):
                        dfs.append(pd.read_csv(local_path))
                    elif local_path.endswith(".json") or local_path.endswith(".jsonl"):
                        dfs.append(pd.read_json(local_path, lines=True))

        if not dfs:
            raise FileNotFoundError(f"FATAL: No parseable data files found in gs://{bucket_name}/{prefix}")

        df = pd.concat(dfs, ignore_index=True)
        row_count = len(df)
        df.to_parquet(self.staging_file, index=False)
        logger.info("Extracted %d real records from GCS to %s", row_count, self.staging_file)
        return row_count

    def transform(self) -> int:
        """Schema-adaptive transformation with sorting by rank ascending."""
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file is empty. Nothing to transform.")
            return 0

        df = pd.read_parquet(self.staging_file)
        raw_count = len(df)
        if raw_count == 0:
            logger.warning("Staging DataFrame is empty. Nothing to transform.")
            return 0

        logger.info("Transforming %d raw records. Raw columns: %s", raw_count, list(df.columns))

        # Standardize column names
        col_mapping = {}
        for col in df.columns:
            clean_col = str(col).replace("\u00a0", " ").strip().lower()
            clean_col = re.sub(r"[^a-zA-Z0-9_]+", "_", clean_col).strip("_")
            if clean_col in ("year_s", "year"):
                clean_col = "years"
            col_mapping[col] = clean_col
        df = df.rename(columns=col_mapping)

        # Coerce rank to numeric
        if "rank" in df.columns:
            df["rank"] = pd.to_numeric(df["rank"].astype(str).str.extract(r"(\d+)", expand=False), errors="coerce").astype("Int64")

        # Coerce shows to numeric
        if "shows" in df.columns:
            df["shows"] = pd.to_numeric(df["shows"].astype(str).str.extract(r"(\d+)", expand=False), errors="coerce").astype("Int64")

        # Standardize string columns
        for col in df.columns:
            if col not in ("rank", "shows"):
                df[col] = df[col].apply(lambda v: str(v).strip() if pd.notna(v) and str(v).strip() not in ("nan", "None", "") else None)

        # Drop rows where all values are null
        df_valid = df.dropna(how="all").copy()
        quarantined = raw_count - len(df_valid)
        if quarantined > 0:
            logger.warning("Quarantined %d fully-null records", quarantined)

        if raw_count > 0 and len(df_valid) == 0:
            logger.error("FATAL: 100%% of %d raw records were quarantined.", raw_count)
            sys.exit(1)

        # Sort deterministically by rank ascending with nulls last
        if "rank" in df_valid.columns:
            df_valid = df_valid.sort_values(by="rank", ascending=True, na_position="last").reset_index(drop=True)

        # Add ingestion audit timestamp
        df_valid["ingested_at"] = datetime.now(timezone.utc).isoformat()

        # Overwrite staging file with cleaned data
        df_valid.to_parquet(self.staging_file, index=False)
        logger.info("Transform complete: raw=%d, valid=%d, quarantined=%d", raw_count, len(df_valid), quarantined)
        return len(df_valid)

    def load(self) -> bool:
        """Loads staged records into BigQuery destination table."""
        logger.info("Loading staged file %s into BigQuery (analytics.test03)...", self.staging_file)
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file %s is empty or missing. Skipping load phase.", self.staging_file)
            return True

        project_id = os.getenv("GCP_PROJECT_ID") or os.getenv("PROJECT_ID") or os.getenv("GOOGLE_CLOUD_PROJECT") or "upbeat-repeater-477110-q6"
        dataset_id = os.getenv("BIGQUERY_DATASET") or "analytics"
        table_id = os.getenv("BIGQUERY_TABLE") or "test03"
        write_mode = "overwrite"

        from google.cloud import bigquery
        try:
            client = bigquery.Client(project=project_id)
        except Exception as client_init_err:
            logger.critical("FATAL: Unable to initialize BigQuery client: %s", client_init_err)
            raise EnvironmentError(f"FATAL: Unable to initialize BigQuery client: {client_init_err}") from client_init_err

        table_ref = f"{project_id}.{dataset_id}.{table_id}"

        # Ensure target dataset exists
        dataset_ref = client.dataset(dataset_id, project=project_id)
        ds = bigquery.Dataset(dataset_ref)
        ds.location = os.getenv("BQ_LOCATION", "us-central1")
        client.create_dataset(ds, exists_ok=True)
        logger.info("Ensured target BigQuery dataset '%s' exists.", dataset_ref)

        df = pd.read_parquet(self.staging_file)

        job_config = bigquery.LoadJobConfig(
            write_disposition=bigquery.WriteDisposition.WRITE_TRUNCATE if write_mode == "overwrite" else bigquery.WriteDisposition.WRITE_APPEND,
            create_disposition=bigquery.CreateDisposition.CREATE_IF_NEEDED,
        )

        schema_file = None
        for cand in [
            os.path.join("schemas", "test03_schema.json"),
            os.path.join("server", "schemas", "test03_schema.json"),
        ]:
            if os.path.isfile(cand):
                schema_file = cand
                break

        if schema_file:
            with open(schema_file, "r") as sf:
                schema_data = json.load(sf)
            schema_fields = []
            for item in schema_data:
                schema_fields.append(
                    bigquery.SchemaField(
                        name=item["name"],
                        field_type=item["type"],
                        mode=item.get("mode", "NULLABLE"),
                        description=item.get("description", "")
                    )
                )
            job_config.schema = schema_fields

            # Type coercion matching schema
            for field in schema_fields:
                col = field.name
                f_type = field.field_type.upper()
                if col in df.columns:
                    if f_type in ("INTEGER", "INT64"):
                        df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")
                    elif f_type in ("TIMESTAMP", "DATETIME"):
                        df[col] = pd.to_datetime(df[col], errors="coerce", utc=True)
                    elif f_type == "STRING":
                        df[col] = df[col].apply(lambda v: str(v) if pd.notna(v) else None)
        else:
            job_config.autodetect = True

        try:
            job = client.load_table_from_dataframe(df, table_ref, job_config=job_config)
            job.result()
        except Exception as load_err:
            logger.error("Primary load_table_from_dataframe failed: %s. Re-raising.", load_err)
            raise RuntimeError(f"BigQuery load failed: {load_err}") from load_err

        logger.info("Successfully loaded %d records into BigQuery table: %s", len(df), table_ref)
        return True

    def run(self) -> int:
        """Executes the end-to-end connector pipeline with fail-fast semantics."""
        logger.info("=== Starting Connector Pipeline Execution ===")
        records = self.extract()
        if records == 0:
            logger.warning("Extraction completed with 0 records.")
        valid_count = self.transform()
        if records > 0 and valid_count == 0:
            logger.error("FATAL: Extracted %d records but 0 survived transformation.", records)
            return 1
        self.load()
        logger.info("=== Pipeline Execution Finished Successfully ===")
        return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Connector Pipeline Runner")
    parser.add_argument("--date", help="Execution date (YYYY-MM-DD)", default=None)
    args = parser.parse_args()

    try:
        runner = PipelineRunner(execution_date=args.date)
        exit_code = runner.run()
        if exit_code != 0:
            sys.exit(1)
        sys.exit(0)
    except Exception as exc:
        logger.critical("Pipeline failed with unhandled error: %s", exc, exc_info=True)
        sys.exit(1)
