"""Standalone Connector Pipeline: sales_order_etl
Generated by SDLC Data Engineer Agent.
Architecture: GCS -> Local Staging -> BIGQUERY
Mock dummy data generation is completely disabled — real extraction & loading only.
"""
import os
import sys
import json
import logging
import argparse
from datetime import datetime

try:
    import pandas as pd
except ImportError:
    pd = None

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [%(name)s] %(message)s",
)
logger = logging.getLogger("sales_order_etl")


class PipelineRunner:
    def __init__(self, execution_date: str = None):
        self.execution_date = execution_date or datetime.utcnow().strftime("%Y-%m-%d")
        self.staging_dir = os.path.join("staging", "sales_order_etl", self.execution_date)
        os.makedirs(self.staging_dir, exist_ok=True)
        self.staging_file = os.path.join(self.staging_dir, "data.parquet")

    def extract(self) -> int:
        """Extracts data from real gcs into staging format using GCSReader."""
        logger.info("Starting real extraction from source: gcs...")
        if pd is None:
            raise RuntimeError("FATAL: pandas is required for pipeline execution.")

        from src.ingestion.gcs_reader import GCSReader
        bucket_name = os.getenv("GCS_SOURCE_BUCKET") or os.getenv("GCS_BUCKET_NAME") or "sdlc-workspec-store"
        prefix = os.getenv("GCS_SOURCE_PREFIX") or os.getenv("GCS_FILE_PATH") or "etl/data/raw_sales_data.csv"
        gcs_uri = f"gs://{bucket_name}/{prefix}"

        logger.info("Ingesting real CSV data from %s", gcs_uri)
        reader = GCSReader()
        df = reader.read_csv(gcs_uri=gcs_uri)
        row_count = len(df)
        df.to_parquet(self.staging_file, index=False)
        logger.info("Extracted %d real records from GCS to %s", row_count, self.staging_file)
        return row_count

    def transform(self) -> int:
        """Schema-adaptive transformation with flexible parsing."""
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file is empty. Nothing to transform.")
            return 0

        df = pd.read_parquet(self.staging_file)
        raw_count = len(df)
        if raw_count == 0:
            logger.warning("Staging DataFrame is empty. Nothing to transform.")
            return 0

        logger.info("Transforming %d raw records. Columns: %s", raw_count, list(df.columns))

        import re
        _FOOTNOTE_RE = re.compile(r"\[[^\]]*\]")
        _NUMERIC_STRIP_RE = re.compile(r"[,$€£¥\s\u00a0]")

        def _normalize_numeric_series(series: pd.Series) -> pd.Series:
            return (
                series.astype(str)
                .str.replace(_FOOTNOTE_RE, "", regex=True)
                .str.replace(_NUMERIC_STRIP_RE, "", regex=True)
                .str.strip()
            )

        df.columns = [
            re.sub(r"[^a-zA-Z0-9_]+", "_", str(col).strip().lower()).strip("_")
            for col in df.columns
        ]
        logger.info("Standardized columns: %s", list(df.columns))

        for col in df.columns:
            if pd.api.types.is_string_dtype(df[col]) or pd.api.types.is_object_dtype(df[col]):
                sample = df[col].dropna().head(5)
                if not sample.empty:
                    parsed = pd.to_datetime(sample, errors="coerce")
                    if parsed.notna().sum() >= max(1, len(sample) * 0.6):
                        df[col] = pd.to_datetime(df[col], errors="coerce")
                        logger.info("Auto-parsed column %s as TIMESTAMP", col)

        for col in df.columns:
            if pd.api.types.is_string_dtype(df[col]) or pd.api.types.is_object_dtype(df[col]):
                sample = df[col].dropna().head(10)
                if not sample.empty:
                    cleaned_sample = _normalize_numeric_series(sample)
                    coerced = pd.to_numeric(cleaned_sample, errors="coerce")
                    if coerced.notna().sum() >= max(1, len(sample) * 0.8):
                        _coerced = pd.to_numeric(_normalize_numeric_series(df[col]), errors="coerce")
                        _valid = _coerced.dropna()
                        if not _valid.empty and (_valid % 1 == 0).all():
                            df[col] = _coerced.astype("Int64")
                        else:
                            df[col] = _coerced
                        logger.info("Auto-coerced column %s to numeric", col)

        for col in df.select_dtypes(include=["object", "string"]).columns:
            df[col] = df[col].astype(str).str.strip()
            df[col] = df[col].replace({"nan": None, "None": None, "": None})

        if "order_id" in df.columns:
            df = df.drop_duplicates(subset=["order_id"], keep="last")

        if "created_at" in df.columns and "order_date" not in df.columns:
            df["order_date"] = pd.to_datetime(df["created_at"]).dt.date

        df_valid = df.dropna(how="all")
        quarantined = raw_count - len(df_valid)
        if quarantined > 0:
            logger.warning("Quarantined %d fully-null records", quarantined)

        if raw_count > 0 and len(df_valid) == 0:
            logger.error("FATAL: 100%% of %d raw records were quarantined.", raw_count)
            sys.exit(1)

        df_valid = df_valid.copy()
        df_valid["ingested_at"] = datetime.utcnow()

        df_valid.to_parquet(self.staging_file, index=False)
        logger.info(
            "Transform complete: raw=%d, valid=%d, quarantined=%d",
            raw_count, len(df_valid), quarantined,
        )
        return len(df_valid)

    def load(self) -> bool:
        """Loads staged records into real BigQuery destination using BigQueryWriter."""
        logger.info("Loading staged file %s into BigQuery...", self.staging_file)
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file %s is empty or missing. Skipping load phase.", self.staging_file)
            return True

        from src.loader.bigquery_writer import BigQueryWriter
        df = pd.read_parquet(self.staging_file)
        project_id = os.getenv("GCP_PROJECT_ID") or os.getenv("GCP_PROJECT") or "upbeat-repeater-477110-q6"
        dataset_id = os.getenv("BIGQUERY_DATASET") or "analytics"
        table_id = os.getenv("BIGQUERY_TABLE") or "harshada-test1"

        logger.info("Writing %d records to BigQuery %s.%s.%s", len(df), project_id, dataset_id, table_id)
        writer = BigQueryWriter(project_id=project_id)
        loaded_count = writer.write_dataframe(df, dataset_id=dataset_id, table_id=table_id, partition_field="order_date")
        logger.info("Successfully loaded %d records into BigQuery table: %s.%s.%s", loaded_count, project_id, dataset_id, table_id)
        return True

    def run(self) -> int:
        """Executes the end-to-end connector pipeline with fail-fast semantics."""
        logger.info("=== Starting Connector Pipeline Execution ===")
        try:
            records = self.extract()
            if records == 0:
                logger.warning("Extraction completed with 0 records.")
            valid_count = self.transform()
            if records > 0 and valid_count == 0:
                logger.error("FATAL: Extracted %d records but 0 survived transformation.", records)
                return 1
            self.load()
            logger.info("=== Pipeline Execution Finished Successfully ===")
            return 0
        except SystemExit:
            raise
        except Exception as exc:
            logger.critical("Pipeline execution FAILED: %s", exc, exc_info=True)
            raise RuntimeError(f"Pipeline execution failed: {exc}") from exc


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Connector Pipeline Runner")
    parser.add_argument("--date", help="Execution date (YYYY-MM-DD)", default=None)
    args = parser.parse_args()

    try:
        runner = PipelineRunner(execution_date=args.date)
        exit_code = runner.run()
        if exit_code != 0:
            sys.exit(1)
        sys.exit(0)
    except Exception as exc:
        logger.critical("Pipeline failed with unhandled error: %s", exc, exc_info=True)
        sys.exit(1)
