"""Standalone Connector Pipeline Runner: test3_etl
Generated by SDLC Data Engineer Agent.
Architecture: GCS -> Transform -> BIGQUERY
Mock dummy data generation is completely disabled — real extraction & loading only.
"""
import os
import sys
import logging
import argparse
from datetime import datetime
from pipeline.extractor import GCSExtractor
from pipeline.transformer import DataTransformer
from pipeline.loader import BigQueryLoader

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [%(name)s] %(message)s",
)
logger = logging.getLogger("test3_etl")


class PipelineRunner:
    """Executes the test3 ETL pipeline."""

    def __init__(self, execution_date: str = None, exchange_rate: float = 83.5):
        self.execution_date = execution_date or datetime.utcnow().strftime("%Y-%m-%d")
        self.exchange_rate = exchange_rate

    def run(self) -> int:
        """Executes the full pipeline and returns exit status code (0 for success, 1 for failure)."""
        logger.info("=== Starting Connector Pipeline Execution for test3_etl ===")
        try:
            source_uri = os.getenv("GCS_SOURCE_URI", "gs://sdlc-workspec-store/etl/data/test_dynamic_etl_gmt.csv")
            project_id = os.getenv("GCP_PROJECT_ID") or os.getenv("PROJECT_ID") or "upbeat-repeater-477110-q6"
            dataset_id = os.getenv("BIGQUERY_DATASET", "analytics")
            table_id = os.getenv("BIGQUERY_TABLE", "test3")

            extractor = GCSExtractor(gcs_uri=source_uri)
            df_raw = extractor.extract()
            if df_raw is None or len(df_raw) == 0:
                logger.warning("Extraction completed with 0 records.")

            transformer = DataTransformer(exchange_rate=self.exchange_rate)
            df_valid = transformer.transform(df_raw)

            if len(df_raw) > 0 and len(df_valid) == 0:
                logger.error("FATAL: Extracted %d records but 0 survived transformation.", len(df_raw))
                sys.exit(1)

            loader = BigQueryLoader(
                project_id=project_id,
                dataset_id=dataset_id,
                table_id=table_id,
                write_mode="overwrite",
            )
            loader.load(df_valid)

            logger.info("=== Pipeline Execution Finished Successfully ===")
            return 0
        except Exception as exc:
            logger.critical("Pipeline execution FAILED: %s", exc, exc_info=True)
            sys.exit(1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Connector Pipeline Runner")
    parser.add_argument("--date", help="Execution date (YYYY-MM-DD)", default=None)
    parser.add_argument("--exchange-rate", type=float, help="Exchange rate USD to INR", default=83.5)
    args = parser.parse_args()

    runner = PipelineRunner(execution_date=args.date, exchange_rate=args.exchange_rate)
    exit_code = runner.run()
    sys.exit(exit_code)
