"""Standalone Connector Pipeline: postgres_to_bigquery_scrum_430
Generated by SDLC Data Engineer Agent.
Architecture: POSTGRESQL -> Local Staging -> BIGQUERY
Mock dummy data generation is completely disabled — real extraction & loading only.
"""
import os
import sys
import json
import logging
import argparse
from datetime import datetime
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import google.auth
from google.cloud import bigquery
from google.cloud.exceptions import NotFound, GoogleCloudError
import sqlalchemy
from google.cloud.sql.connector import Connector, IPTypes

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [%(name)s] %(message)s",
)
logger = logging.getLogger("postgres_to_bigquery_scrum_430")


class PipelineRunner:
    def __init__(self, execution_date: str = None):
        self.execution_date = execution_date or datetime.utcnow().strftime("%Y-%m-%d")
        self.staging_dir = os.path.join("staging", "postgres_to_bigquery_scrum_430", self.execution_date)
        os.makedirs(self.staging_dir, exist_ok=True)
        self.staging_file = os.path.join(self.staging_dir, "data.parquet")

    def extract(self) -> int:
        """Extracts data from real postgresql into staging format.
        
        Zero-mock policy: if credentials or sources are unavailable, raises an error immediately.
        """
        logger.info("Starting real extraction from source: postgresql...")
        db_url = os.getenv("DATABASE_URL") or os.getenv("POSTGRES_URL")
        sql_engine = None
        sql_connector = None

        instance_connection_name = (
            os.getenv("INSTANCE_CONNECTION_NAME")
            or os.getenv("POSTGRES_INSTANCE_CONNECTION_NAME")
            or os.getenv("CLOUD_SQL_CONNECTION_NAME")
            or ""
        )
        host = os.getenv("POSTGRES_HOST") or os.getenv("DB_HOST", "")
        if not instance_connection_name and host and host.count(":") == 2:
            instance_connection_name = host
            host = ""

        port = os.getenv("POSTGRES_PORT") or os.getenv("DB_PORT", "5432")
        user = os.getenv("POSTGRES_USER") or os.getenv("DB_USER", "")
        dbname = os.getenv("POSTGRES_DB") or os.getenv("DB_NAME", "")

        # Cloud SQL Python Connector with mandatory IAM Authentication
        if instance_connection_name and user:
            try:
                logger.info(
                    "Connecting via Cloud SQL Python Connector for %s (IAM auth, user=%s)",
                    instance_connection_name, user
                )
                sql_connector = Connector()
                _ip_type = IPTypes.PRIVATE if (os.getenv("CLOUD_SQL_IP_TYPE", "PRIVATE").upper() == "PRIVATE") else IPTypes.PUBLIC
                def _getconn():
                    return sql_connector.connect(
                        instance_connection_name,
                        "pg8000",
                        user=user,
                        db=dbname,
                        enable_iam_auth=True,  # ALWAYS True — IAM auth is mandatory
                        ip_type=_ip_type,
                    )
                sql_engine = sqlalchemy.create_engine("postgresql+pg8000://", creator=_getconn)
            except Exception as _conn_err:
                logger.error(
                    "FATAL: Cloud SQL Python Connector initialization failed: %s. "
                    "Ensure cloud-sql-python-connector is in requirements.txt and "
                    "INSTANCE_CONNECTION_NAME, POSTGRES_USER, POSTGRES_DB are set correctly.",
                    _conn_err
                )
                raise RuntimeError(f"Cloud SQL connector failed: {_conn_err}") from _conn_err

        con_target = sql_engine if sql_engine is not None else db_url
        if not con_target:
            raise EnvironmentError(
                "FATAL: Database connection parameters missing. "
                "Provide INSTANCE_CONNECTION_NAME + POSTGRES_USER + POSTGRES_DB for Cloud SQL IAM auth, "
                "or DATABASE_URL for direct connection. Mock dummy data is disabled."
            )

        query = "SELECT * FROM test_data"
        logger.info("Executing extraction query against PostgreSQL: %s", query)
        try:
            df = pd.read_sql(query, con=con_target)
        finally:
            if sql_engine is not None:
                sql_engine.dispose()
            if sql_connector is not None:
                sql_connector.close()

        row_count = len(df)
        df.to_parquet(self.staging_file, index=False)
        logger.info("Extracted %d real records to %s", row_count, self.staging_file)
        return row_count

    def transform(self) -> int:
        """Schema-adaptive transformation with flexible parsing."""
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file is empty. Nothing to transform.")
            return 0

        df = pd.read_parquet(self.staging_file)
        raw_count = len(df)
        if raw_count == 0:
            logger.warning("Staging DataFrame is empty. Nothing to transform.")
            return 0

        logger.info("Transforming %d raw records. Columns: %s", raw_count, list(df.columns))

        import re
        _FOOTNOTE_RE = re.compile(r"\[[^\]]*\]")
        _NUMERIC_STRIP_RE = re.compile(r"[,$€£¥\s\u00a0]")

        df.columns = [
            re.sub(r"[^a-zA-Z0-9_]+", "_", str(col).strip().lower()).strip("_")
            for col in df.columns
        ]
        logger.info("Standardized columns: %s", list(df.columns))

        # Specification-Driven Column Transformations
        if "id" in df.columns:
            df["id"] = df["id"].astype(str).str.strip().replace({"nan": None, "None": None, "": None})
            logger.info("Applied specification transformation to id -> STRING")
        if "payload_data" in df.columns:
            df["payload_data"] = df["payload_data"].astype(str).str.strip().replace({"nan": None, "None": None, "": None})
            logger.info("Applied specification transformation to payload_data -> STRING")
        if "status" in df.columns:
            df["status"] = df["status"].astype(str).str.strip().replace({"nan": None, "None": None, "": None})
            logger.info("Applied specification transformation to status -> STRING")
        if "source_created_at" in df.columns:
            df["source_created_at"] = pd.to_datetime(df["source_created_at"], errors="coerce")
            logger.info("Applied specification transformation to source_created_at -> TIMESTAMP")

        # Standardize remaining string columns
        for col in df.select_dtypes(include=["object", "string"]).columns:
            df[col] = df[col].astype(str).str.strip().replace({"nan": None, "None": None, "": None})

        # Drop rows where ALL columns are null
        df_valid = df.dropna(how="all")
        quarantined = raw_count - len(df_valid)
        if quarantined > 0:
            logger.warning("Quarantined %d fully-null records", quarantined)

        # Circuit breaker
        if raw_count > 0 and len(df_valid) == 0:
            logger.error(
                "FATAL: 100%% of %d raw records were quarantined. "
                "This indicates a schema contract violation between "
                "the source data and the pipeline expectations. "
                "Failing the pipeline.", raw_count
            )
            sys.exit(1)

        # Add ingestion audit timestamp
        df_valid = df_valid.copy()
        df_valid["ingested_at"] = datetime.utcnow().isoformat()

        # Overwrite staging file with cleaned data
        df_valid.to_parquet(self.staging_file, index=False)
        logger.info(
            "Transform complete: raw=%d, valid=%d, quarantined=%d",
            raw_count, len(df_valid), quarantined,
        )
        return len(df_valid)

    def load(self) -> bool:
        """Loads staged records into real bigquery destination."""
        logger.info("Loading staged file %s into bigquery (analytics.postgres_test5)...", self.staging_file)
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file %s is empty or missing. Skipping load phase.", self.staging_file)
            return True
        project_id = os.getenv("GCP_PROJECT_ID") or os.getenv("PROJECT_ID") or os.getenv("GOOGLE_CLOUD_PROJECT") or os.getenv("GCLOUD_PROJECT")
        dataset_id = os.getenv("BIGQUERY_DATASET") or "analytics"
        table_id = os.getenv("BIGQUERY_TABLE") or "postgres_test5"
        write_mode = "append"

        if not project_id:
            try:
                _, project_id = google.auth.default()
            except (google.auth.exceptions.DefaultCredentialsError, AttributeError):
                project_id = None
        try:
            client = bigquery.Client(project=project_id) if project_id else bigquery.Client()
            if not project_id and getattr(client, "project", None):
                project_id = client.project
        except Exception as client_init_err:
            raise EnvironmentError(
                f"FATAL: Unable to initialize BigQuery client (project_id='{project_id}'): {client_init_err}"
            ) from client_init_err

        table_ref = f"{project_id}.{dataset_id}.{table_id}" if project_id else f"{dataset_id}.{table_id}"

        # Pre-create target dataset if it does not exist
        try:
            dataset_ref = client.dataset(dataset_id, project=project_id)
            try:
                client.get_dataset(dataset_ref)
            except NotFound:
                ds = bigquery.Dataset(dataset_ref)
                ds.location = os.getenv("BQ_LOCATION", "us-central1")
                client.create_dataset(ds, exists_ok=True)
                logger.info("Ensured target BigQuery dataset '%s' exists.", dataset_ref)
        except GoogleCloudError as ds_err:
            logger.warning("Dataset pre-check warning for '%s': %s", dataset_id, ds_err)

        df = pd.read_parquet(self.staging_file)

        job_config = bigquery.LoadJobConfig(
            write_disposition=bigquery.WriteDisposition.WRITE_APPEND if write_mode == "append" else bigquery.WriteDisposition.WRITE_TRUNCATE,
            create_disposition=bigquery.CreateDisposition.CREATE_IF_NEEDED,
        )
        schema_file = None
        for cand in [
            os.path.join("schemas", "postgres_test5_schema.json"),
            os.path.join("schemas", "postgres_to_bigquery_scrum_430_schema.json"),
            os.path.join("schemas", "target_table_schema.json"),
        ]:
            if os.path.isfile(cand):
                schema_file = cand
                break
        if schema_file:
            try:
                raw_schema = client.schema_from_json(schema_file)
                # Reconcile schema against actual DataFrame columns
                reconciled_schema = []
                for field in raw_schema:
                    if field.name not in df.columns:
                        df[field.name] = None
                        reconciled_schema.append(
                            bigquery.SchemaField(
                                name=field.name,
                                field_type=field.field_type,
                                mode="NULLABLE",
                                description=field.description,
                            )
                        )
                        logger.info("Reconciled missing schema column '%s' in DataFrame with NULLs.", field.name)
                    else:
                        reconciled_schema.append(field)

                schema_col_names = {sf.name for sf in raw_schema}
                for col in df.columns:
                    if col not in schema_col_names:
                        reconciled_schema.append(
                            bigquery.SchemaField(
                                name=col,
                                field_type="STRING",
                                mode="NULLABLE",
                                description=f"Dynamically discovered column '{col}'",
                            )
                        )
                        logger.info("Appended dynamically discovered column '%s' to BigQuery schema.", col)

                # Type-safe coercion to prevent pyarrow conversion errors
                for field in reconciled_schema:
                    col = field.name
                    f_type = field.field_type.upper()
                    if col in df.columns:
                        try:
                            if f_type in ("INTEGER", "INT64"):
                                df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")
                            elif f_type in ("FLOAT", "FLOAT64", "NUMERIC", "BIGNUMERIC"):
                                df[col] = pd.to_numeric(df[col], errors="coerce")
                            elif f_type in ("TIMESTAMP", "DATETIME"):
                                df[col] = pd.to_datetime(df[col], errors="coerce", utc=True)
                            elif f_type in ("BOOLEAN", "BOOL"):
                                df[col] = df[col].map(
                                    lambda v: True if str(v).strip().lower() in ("true", "1", "t", "yes")
                                    else (False if str(v).strip().lower() in ("false", "0", "f", "no") else None)
                                    if pd.notna(v) else None
                                ).astype("boolean")
                            elif f_type == "STRING":
                                df[col] = df[col].apply(lambda v: str(v) if pd.notna(v) else None)
                        except (ValueError, TypeError) as cast_err:
                            logger.warning("Non-fatal type casting warning for column '%s' (%s): %s", col, f_type, cast_err)

                job_config.schema = reconciled_schema
                logger.info("Attached and reconciled explicit BigQuery schema from %s (%d fields)", schema_file, len(reconciled_schema))
            except (ValueError, KeyError, TypeError, OSError) as schema_err:
                logger.warning("Could not attach schema from %s: %s; falling back to autodetect", schema_file, schema_err)
                job_config.autodetect = True
        else:
            job_config.autodetect = True

        if write_mode == "append":
            job_config.schema_update_options = [
                bigquery.SchemaUpdateOption.ALLOW_FIELD_ADDITION,
                bigquery.SchemaUpdateOption.ALLOW_FIELD_RELAXATION,
            ]

        try:
            job = client.load_table_from_dataframe(df, table_ref, job_config=job_config)
            job.result()  # Blocks until BigQuery load completes
        except GoogleCloudError as load_err:
            logger.warning("Primary load_table_from_dataframe failed: %s. Attempting resilient JSON fallback...", load_err)
            records = df.to_dict(orient="records")
            fallback_config = bigquery.LoadJobConfig(
                write_disposition=bigquery.WriteDisposition.WRITE_APPEND if write_mode == "append" else bigquery.WriteDisposition.WRITE_TRUNCATE,
                create_disposition=bigquery.CreateDisposition.CREATE_IF_NEEDED,
                autodetect=True,
            )
            fallback_job = client.load_table_from_json(records, table_ref, job_config=fallback_config)
            fallback_job.result()

        logger.info("Successfully loaded %d records into BigQuery table: %s", len(df), table_ref)
        return True

    def run(self) -> int:
        """Executes the end-to-end connector pipeline with fail-fast semantics."""
        logger.info("=== Starting Connector Pipeline Execution ===")
        try:
            records = self.extract()
            if records == 0:
                logger.warning("Extraction completed with 0 records.")
            valid_count = self.transform()
            if records > 0 and valid_count == 0:
                logger.error(
                    "FATAL: Extracted %d records but 0 survived transformation. "
                    "Schema contract violation — failing pipeline.", records
                )
                raise RuntimeError("0 records survived transformation")
            self.load()
            logger.info("=== Pipeline Execution Finished Successfully ===")
            return 0
        except SystemExit:
            raise
        except Exception as exc:
            logger.critical("Pipeline execution FAILED: %s", exc, exc_info=True)
            raise


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Connector Pipeline Runner")
    parser.add_argument("--date", help="Execution date (YYYY-MM-DD)", default=None)
    args = parser.parse_args()

    try:
        runner = PipelineRunner(execution_date=args.date)
        exit_code = runner.run()
        if exit_code != 0:
            sys.exit(1)
        sys.exit(0)
    except Exception as exc:
        logger.critical("Pipeline failed with unhandled error: %s", exc, exc_info=True)
        sys.exit(1)
