"""Airflow DAG: kttest04_dag
Generated by SDLC Data Engineer Agent.
Description: ETL Pipeline to ingest concert tour CSV from GCS, sort by rank, and load into BigQuery table kttest04
"""
from datetime import datetime, timedelta
import logging

from airflow import DAG
from airflow.operators.python import PythonOperator

logger = logging.getLogger(__name__)

default_args = {
    "owner": "data-engineering",
    "depends_on_past": False,
    "start_date": datetime(2025, 1, 1),
    "email_on_failure": False,
    "email_on_retry": False,
    "retries": 2,
    "retry_delay": timedelta(minutes=5),
}


def _run_etl_pipeline(**context):
    """Executes the full GCS to BigQuery ETL pipeline."""
    from server.config import get_config
    from server.pipeline import run_pipeline

    logger.info("Executing ETL pipeline in Airflow task context...")
    config = get_config()
    result = run_pipeline(config)
    logger.info("Pipeline executed successfully: %s", result.status)
    return result.model_dump()


with DAG(
    dag_id="kttest04_dag",
    default_args=default_args,
    description="ETL Pipeline to ingest concert tour CSV from GCS, sort by rank, and load into BigQuery table kttest04",
    schedule_interval="@daily",
    catchup=False,
    tags=["etl", "gcs", "bigquery", "kttest04"],
) as dag:

    run_pipeline_task = PythonOperator(
        task_id="run_kttest04_etl_pipeline",
        python_callable=_run_etl_pipeline,
    )

    run_pipeline_task
