"""Airflow DAG: postgres_to_bigquery_dag
Generated by SDLC Data Engineer Agent.
Description: ETL pipeline extracting from Cloud SQL PostgreSQL and loading into BigQuery
"""
from datetime import datetime, timedelta
import logging

from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.operators.bash import BashOperator
try:
    from airflow.providers.google.cloud.transfers.gcs_to_bigquery import GCSToBigQueryOperator
    from airflow.providers.google.cloud.operators.bigquery import BigQueryInsertJobOperator
except ImportError:
    GCSToBigQueryOperator = None
    BigQueryInsertJobOperator = None

logger = logging.getLogger(__name__)

default_args = {
    "owner": "data-engineering",
    "depends_on_past": False,
    "start_date": datetime(2025, 1, 1),
    "email_on_failure": False,
    "email_on_retry": False,
    "retries": 2,
    "retry_delay": timedelta(minutes=5),
}

def _log_pipeline_start(**context):
    logger.info("Starting pipeline execution for execution_date=%s", context.get("ds"))

def _log_pipeline_complete(**context):
    logger.info("Pipeline execution finished successfully for execution_date=%s", context.get("ds"))

with DAG(
    dag_id="postgres_to_bigquery_dag",
    default_args=default_args,
    description="ETL pipeline extracting from Cloud SQL PostgreSQL and loading into BigQuery",
    schedule_interval="@daily",
    catchup=False,
    tags=["postgres", "bigquery", "etl"],
) as dag:

    start_task = PythonOperator(
        task_id="start_pipeline",
        python_callable=_log_pipeline_start,
        provide_context=True,
    )

    end_task = PythonOperator(
        task_id="end_pipeline",
        python_callable=_log_pipeline_complete,
        provide_context=True,
    )

    start_task >> end_task
