"""Airflow DAG: sales_orders_etl_pipeline
Generated by SDLC Data Engineer Agent.
Description: Extract sales orders from PostgreSQL, validate/cleanse records, and load to BigQuery fct_sales_orders partitioned by order date.
"""
from datetime import datetime, timedelta
import logging

from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.operators.bash import BashOperator
try:
    from airflow.providers.google.cloud.transfers.gcs_to_bigquery import GCSToBigQueryOperator
    from airflow.providers.google.cloud.operators.bigquery import BigQueryInsertJobOperator
except ImportError:
    GCSToBigQueryOperator = None
    BigQueryInsertJobOperator = None

logger = logging.getLogger(__name__)

default_args = {
    "owner": "data-engineering",
    "depends_on_past": False,
    "start_date": datetime(2025, 1, 1),
    "email_on_failure": False,
    "email_on_retry": False,
    "retries": 2,
    "retry_delay": timedelta(minutes=5),
}

def _log_pipeline_start(**context):
    logger.info("Starting pipeline execution for execution_date=%s", context.get("ds"))

def _log_pipeline_complete(**context):
    logger.info("Pipeline execution finished successfully for execution_date=%s", context.get("ds"))

with DAG(
    dag_id="sales_orders_etl_pipeline",
    default_args=default_args,
    description="Extract sales orders from PostgreSQL, validate/cleanse records, and load to BigQuery fct_sales_orders partitioned by order date.",
    schedule_interval="0 2 * * *",
    catchup=False,
    tags=["sales", "etl", "bigquery", "postgresql"],
) as dag:

    start_task = PythonOperator(
        task_id="start_pipeline",
        python_callable=_log_pipeline_start,
        provide_context=True,
    )

    end_task = PythonOperator(
        task_id="end_pipeline",
        python_callable=_log_pipeline_complete,
        provide_context=True,
    )

    start_task >> end_task
