"""Airflow DAG: sales_data_etl_pipeline
Generated by SDLC Data Engineer Agent for SCRUM-290.
Description: ETL pipeline to extract raw sales orders from PostgreSQL, filter invalid records, and load into BigQuery fct_sales_orders partitioned by order_date.
"""
from datetime import datetime, timedelta
import logging

try:
    from airflow import DAG
    from airflow.operators.python import PythonOperator
    AIRFLOW_AVAILABLE = True
except ImportError:
    AIRFLOW_AVAILABLE = False

logger = logging.getLogger(__name__)

default_args = {
    "owner": "data-engineering",
    "depends_on_past": False,
    "start_date": datetime(2025, 1, 1),
    "email_on_failure": False,
    "email_on_retry": False,
    "retries": 2,
    "retry_delay": timedelta(minutes=5),
}

def execute_sales_etl(**context):
    """
    Executes the sales ETL pipeline run for the given execution date.
    """
    logger.info("Executing Sales ETL pipeline for date: %s", context.get("ds"))
    try:
        from server.pipeline.extractor import PostgresExtractor
        from server.pipeline.validator import DataValidator
        from server.pipeline.transformer import DataTransformer
        from server.pipeline.loader import BigQueryLoader
        from server.schemas import PipelineRunRequest
        from server.main import run_pipeline_job

        req = PipelineRunRequest()
        result = run_pipeline_job(req)
        logger.info("Sales ETL pipeline execution completed: %s", result.model_dump())
        return result.model_dump()
    except Exception as e:
        logger.error("Sales ETL execution failed: %s", e)
        raise

if AIRFLOW_AVAILABLE:
    dag = DAG(
        dag_id="sales_data_etl_pipeline",
        default_args=default_args,
        description="ETL pipeline to extract raw sales orders from PostgreSQL, filter invalid records, and load into BigQuery fct_sales_orders partitioned by order_date.",
        schedule_interval="@daily",
        catchup=False,
        tags=["sales", "etl", "bigquery", "postgresql"],
    )

    etl_task = PythonOperator(
        task_id="extract_validate_load_sales",
        python_callable=execute_sales_etl,
        provide_context=True,
        dag=dag,
    )
